### ISSUE TITLE
Summer of Hacks 2015

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#101]
The Summer of Hacks. Enough said!

This is a placeholder for the event series, to capture tasks which flow over all events. Each event will be its own issue.

* [International NodeSchool Day](https://github.com/jsoxford/jsoxford.github.com/issues/102)
* Sushack!
* [International Nodebots Day](https://github.com/jsoxford/jsoxford.github.com/issues/103)
* [RailsBridge](https://github.com/jsoxford/jsoxford.github.com/issues/104)
* [JSOxHack](https://github.com/jsoxford/jsoxford.github.com/issues/105)

#### Organisation

- [x] Should we have a logo? The RTHack logo made it all feel a bit more professional.
- [x] Work out sponsorship/funding requirements
- [x] Organise sponsorship
  - [x] Haybrook IT
  - [ ] GitHub community
  - [x] Additional hardware/kits for NodeBots
- Let everyone know
  - [x] JSOxford page for Summer of Hacks
  - [x] Digital Oxford
  - [x] Oxford University
  - [x] Brookes University
  - [ ] Oxford Geek Nights

#### Catering

Based (loosely) on last year's events we'll need the following for a comfortable day (per-attendee):

- 2-3 mini-pastries
- 1 burrito
- 2-3 bottles of beer

Snacks work out to around £2.20 per attendee:

- Crisps: 1 large bag per 4 attendees.
- Fruit: bananas went down well, apples and oranges were almost left untouched. A handful of fruit should be enough, but it's good to promote healthy eating :+1:.
- Soft drinks: Sprite, Diet Sprite, Coke, Diet Coke. A mixture, favouring Diet Coke, approx. 2 cans per attendee.
- Coffee/Tea (@benfoxall are WO happy to provide this?)

**Comment by spikeheap** [comment]
I really like this from [#hacksoton](http://hacksoton.com/), maybe on Saturday we can talk about how we can make our events more accessible (or at least look as accessible as they are):

![_hacksoton](https://cloud.githubusercontent.com/assets/464482/7041705/8d2ac0d6-ddd3-11e4-8520-94eff042e225.png)

**Comment by AverageMarcus** [comment]
:+1: I really like that too!

**Comment by richdouglasevans** [comment]
:+1: on the clear expectations banner. Certainly I didn't know what to expect when I sauntered along for my first day with you lot -- The Game Of Life-thon, May 2014 -- and did wonder if I'd "fit."

:+1: on a logo. I felt it did add some small level of polish to the RT Hack Day :smile:

**Comment by LuRsT** [comment]
:+1:

**Comment by spikeheap** [comment]
@richdouglasevans I agree on both points. We could do with a JSOxford member who's keen to logo-ise the event series.

**Comment by benfoxall** [comment]
very boringly - we need to have a bit of instruction for attendees for hack days at WO:

* wifi
* toilets
* where to put rubbish (just found a half-eaten burrito in the recycling bin)

**Comment by AverageMarcus** [comment]
@benfoxall a pretty simple "Welcome" slide/page could provide that info for people on the projector as they come in.

**Comment by benfoxall** [comment]
I was more thinking along the lines of if we have a "this is how we run an event" template - it would be cool to have housekeeping/intro stuff as part of that!

**Comment by spikeheap** [comment]
:+1:

**Comment by AverageMarcus** [comment]
This all happened and was amazing. Only thing left to do now is:
 * [ ] Remove the banner on the website (@benfoxall I think I saw you working on that)
 * [ ] Add a "It was awesome and now over" message to the summer of hacks page
 * [ ] Write up a summer round-up post
