### ISSUE TITLE
2015-08-07/08 RailsBridge

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#104]
This event is on Meetup: http://www.meetup.com/JSOxford/events/222202996/
#### Date
* Friday 7th August 2015, 7pm, InstallFest
* Saturday 8th August 2015, 10am

#### Getting the word out

Advertising this is going to be trickier than our usual events – our target audience probably aren't in out Meetup group and already, and don't follow us on Twitter. My thoughts for getting the word out:

- [x] Tweet to Cucumber (@cucumberbdd) – they've said they'll spread the word
- [x] Get the event into the Bodleian libraries newsletter. @spikeheap can sort that out.
- [x] Get in touch with the Oxford Mail about the SoH and RailsBridge (http://www.oxfordmail.co.uk/events/Oxford/1082026.RailsBridge/)
- [x] Get in touch with Jack FM. They often do adverts and shout-outs, so we might get some coverage there. (http://www.jackfmoxfordshire.co.uk/jacktivities/event/3825/)
- [x] Contact Oxford University (and CS department)
- [x] Contact Oxford Brookes
- [x] Contact big employers in the area. Elsevier, OUP, ???

#### Organisation

- [ ] Raise invoice with Haybrook for sponsorship (@spikeheap has the figures)
- [x] Book pastries
- [x] Purchase snacks/drinks (see #101)

Part of the Summer of Hacks 2015 (#101).

**Comment by richdouglasevans** [comment]
As in [RailsBridge](http://www.railsbridge.org/)?

**Comment by spikeheap** [comment]
Totes :+1:. The idea is to have a JS/HTML/CSS day and a Rails day, both aimed at increasing diversity in tech.

**Comment by spikeheap** [comment]
We could use https://pro.nitrous.io as an editor for people who have issues getting set up. Might be worth playing with it beforehand.

**Comment by spikeheap** [comment]
- [ ] @benfoxall could you send an invoice out to Haybrook to cover this event please?
- [ ] @spikeheap to organise pastries

**Comment by spikeheap** [comment]
This happened. It was pretty damned good. We had a higher dropoff rate than we expected (with only two attendees to the installfest and ~12 to the day), but in hindsight that's to be expected because our target audience was outside the established JSOxford circle. 

Everyone who came seemed super-keen, and it felt (at least to me) as though it was a valuable experience. I certainly learned a lot. 

We had plenty of helpers, so thanks to everyone who came. I'll also tip my hat to Tanya, Sroop and Masha who came up from London for the weekend to help out. That was awesome. 

I'd definitely consider running this again. Both tracks worked well, though some people finished up early and were after subsequent lessons to follow. The RailsBridge material is great, but after the full Rails intro you're after a different approach to keep things fresh. We tried Codecademy which worked well and was very engaging, but some of the code they used was a bit questionable. For next time it would be good to have a short list of stretch goals for people which we could curate from other sources.

We have a few attendees signed up for the JSOxHack, so hopefully they'll come along and continue learning and getting to know everyone.

All in all, it was awesome. Thanks everyone for making it happen.
