### ISSUE TITLE
Write up RTHack post

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#108]
We need a short post for posterity, with a list of the projects people did, how well it went, and possibly some photos :).

This will also help newcomers get a better idea of what to expect from a JSOxford event.

**Comment by AverageMarcus** [comment]
:+1: 

I'll be doing my own write up at some point this week and I know @danielthepope has a write up here: https://danielthepope.wordpress.com/2015/04/12/realtime-hacking-with-jsoxford/

I also took a few photos but haven't come out very well. I may try touching them up a bit,

**Comment by spikeheap** [comment]
:+1:

**Comment by LuRsT** [comment]
:+1:

**Comment by danielthepope** [comment]
How about I try to write a 'JSOxford for beginners' post at some point?

**Comment by spikeheap** [comment]
:+1: that would be great.
