### ISSUE TITLE
Create Jekyll posts for meetup events

### ISSUE THREAD

**Issue by AverageMarcus** [jsoxford/jsoxford.github.com#109]
As part of the build step create Jekyll posts of all meetup events.

This would mean we wouldn't lose past events if we move away from Meetup

 - [ ] Generate file in _posts for each meetup event
 - [ ] Check for updates to old post and regenerate
 - [ ] Update JavaScript to check for updates/new since last build

See #64.

@spikeheap / @benfoxall anything to add?

**Comment by LuRsT** [comment]
:+1:

**Comment by AverageMarcus** [comment]
Fixed in #131
