### ISSUE TITLE
Write up NodeSchool Day post

### ISSUE THREAD

**Issue by richdouglasevans** [jsoxford/jsoxford.github.com#119]
We need a short post for posterity, with a list of the projects people did, how well it went, and possibly some photos. This will also help newcomers get a better idea of what to expect from a JSOxford event.

> _Shamelessly cloned from [here.](https://github.com/jsoxford/jsoxford.github.com/issues/108)_ :smile:

**Comment by richdouglasevans** [comment]
> _"First learn stand, then learn fly. Nature rule, Daniel-san, not mine."_ — Mr. Miyagi, [The Karate Kid](http://www.imdb.com/title/tt0087538/) (1984)

Saturday 23rd of May was [International NodeSchool Day](http://nodeschool.io/international-day/), with workshops focused on grokking [Node.js](https://nodejs.org/) taking place all over the globe.

The canny bods at [JSOxford](http://jsoxford.com/) were running an event locally at [White October's](https://www.whiteoctober.co.uk/) offices in Oxford's hip Cowley suburb as part of their [Summer of Hacks](http://summerofhacks.io/) programme. Intrigued by the thought of spending a day immersed in NodeJS, I duly sauntered along in my [Vibram's](http://www.vibramfivefingers.com/index.htm) to see what was cooking in their Node kitchen. I'm glad I did because the day was proper station.

> _"Station!"_ — Ted, [Bill & Ted's Bogus Journey](http://www.imdb.com/title/tt0101452/) (1991)

## The Morning

The day was structured such that the first half was spent working through the [learnyounode](https://www.github.com/workshopper/learnyounode) workshop. This workshop is introductory Node material, covering topics such as asynchronous IO and the module system.

![learnyounode workshop](https://camo.githubusercontent.com/17955d1d684a9a0b3fd9d5d863393e6e952cc3b4/68747470733a2f2f7261772e6769746875622e636f6d2f72766167672f6c6561726e796f756e6f64652f6d61737465722f6c6561726e796f756e6f64652e706e67)

This material is good and presented well via a lovely command line application. I'd recommend it to my colleagues to bootstrap their Node learning. Some of the error messages were a tad cryptic, but that's easily addressed: one of the attendees even took the time to submit a Pull Request to improve the error message in one of the exercises.

Personally I didn't get much from the material having already covered the content in my earlier explorations of NodeJS. It was good to structure the day this way though, because more experienced folk were thus pushed to pair with less experienced folk and there was plenty of knowledge-sharing and conversation which made me happy.

## The Afternoon

The second half of the day was devoted to "electives": material that covered a specific area of NodeJS to an intermediate level. (Promises, Express, Working With Binary Data, that sort of thing.). Folk were encouraged to pick an elective that interested them, and they could then either pair with like-minded folk or strike out on their own. If folk wanted to continue with the `learnyounode` module they could do that too.

I dipped in and out of a few electives, sampling them and getting a feel for ones that I'll work through on my own time later. The Functional Elective isn't particularly NodeJS-focused -- being more of a general ES5 elective -- but Ryan and I had a fun few minutes working through the trampolining exercise.

I liked that folk could investigate areas of NodeJS that appealed to them. The (slight) downside is that folk fragmented into isolated clusters and a little of the collaborative pair programming vibe was lost. I spent some of the afternoon wandering around asking folk about what they were working on and offering help where I could.

> There was a definite "post burrito" slump after lunch :laughing: Thanks for the awesome lunch [HaybrookIT](http://www.haybrook.co.uk/), you rock!

## The Evening

And then we retired the the pub for some drinks and fine banter. What happened at the pub stays at the pub though, so I will speak no more of it here save to mention that there was krumping.

## What I Wanted From The Day

I use a lot of the [Amazon Web Services](http://aws.amazon.com/) stack in my [day job](http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/order-and-chaos/day-job-r622) and the recent release of [AWS Lambda](http://aws.amazon.com/lambda/) has opened the door to using NodeJS.

I wanted to spend the day knee deep in the mud of NodeJS: I wanted to wiggle my toes deep in the cool muck and get a good feel for the Node ecosystem.

## What I Got From The Day

I spent ~6 hours immersed in NodeJS via the [excellent material](http://nodeschool.io/#workshoppers) provided by the NodeSchool website.

I got to know about a great resource for bootstrapping the folk on my team into NodeJS. I also learned about [cowsay](http://en.wikipedia.org/wiki/Cowsay). Finally, I got to enjoy the company of some great folk that I already know, and got to meet some new folk on the JSOxford scene.

Win.

Many thanks to Ryan and Ben from JSOxford for organising the day, to Sarah from HaybrookIT for sponsoring the event, to the NodeSchool community for providing such sweet resource, and to the folk that attended on the day.

Shout out to Adam for his stirring singalong of The Rains of Castamere. #awesome

> _"Lesson not just karate only. Lesson for whole life. Whole life have a balance."_ — Mr. Miyagi, [The Karate Kid](http://www.imdb.com/title/tt0087538/) (1984)

**Comment by richdouglasevans** [comment]
I didn't take any photos sadly, but I'm sure Ryan can magic some stills from the video that was shot.

**Comment by AverageMarcus** [comment]
@richdouglasevans / @spikeheap / @benfoxall - Are you all happy if I add this as a post now we have authored posts?

**Comment by benfoxall** [comment]
Definitely - this post is beautiful.
