### ISSUE TITLE
Nodebots Hardware Shopping List

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#121]
We need to get some kit for nodebots (#103).  Add comments, and we'll keep this list updated appropriately.

## Espruino × 15 (with spares)

- [x] £10.91	Lobster bands
- [x] £32.26	Optical sensors ($50.80)
- [x] £7.16	Battery leads/connectors
- [x] £37.80	Batteries
- [x] £56.65	Components from Farnell
- [x] £38.97	Distance sensors from eBay
- [ ] Espruino car PCBs (@gfwilliams ordered them, but I can't remember how much they cost). These have arrived, they just need to be paid for.
- [ ] Servos (@gfwilliams had a load, so we just need an invoice for them)
Running total: £183.75

**Comment by spikeheap** [comment]
Hi @benfoxall, 

We want 15 Espruino kits, as we have access to 15 Espruinos from Gordon.

The chassis sets are the same for arduino/espruino, so the costs will be the same either way. The list doesn't need to be split by the board, it just needs to be 15 chassis and enough breadboards to make it all up. 

We do want enough kits that each group can do the same thing - that way we can have a rough plan for the day for everyone to follow. Anyone wanting to hack on their own thing is more than welcome, but it's nice to have some structure for those who don't know what to start on (as was the case with everyone last year).

**Comment by benfoxall** [comment]
@spikeheap - Man, this is still confusing.  Seems a bit like we're going round in circles; I thought we's said yesterday that 3 per team would work, and about an hour ago you said the chassis were different.  Good that we've got this issue.

So, just to clarify:

1. Are we building [sumobots](http://sumobotkit.com/)?
2. It's £13 per sumobot for sensors etc?
3. Do we need an additional breadboard for each sumobot?
4. We've got access to 15 Espruinos from Gordon?

**Comment by spikeheap** [comment]
Hi @benfoxall, no the chassis are compatible with both, they just aren't the ones I'd specced and priced up. We *could* force people into groups of 3, which would probably work fine, but last year there were quite a few people working in pairs and a couple working individually. Finding sponsorship for £345 isn't much different to finding sponsorship for £230, so why would we not aim to provide enough for everyone to work roughly in pairs if they want to?

1. Sumobots look awesome, but they only really work if many teams complete them. My worry was that people can get left behind and it's a bit demoralising if you realise you're not going to make it in time. Also, sumobots is a competition, which can be intimidating for some first-time people to attend, so I was keen to not make it competitive (and sumobots might suck if it's not a comp unless we've got some creative ideas?).
2. The £13 was a rough guesstimate of sensors and bits, and it's probably a reasonable amount to put towards car/sumobot/whatever, though we can cut bits out of here if we're really struggling.
3. A breadboard per bot/team is a good starting point. Gordon was talking about knocking up a PCB which would mean we didn't need the breadboard for the espruinos, but we need to make sure we can source the car kits before going down that route. It might also be possible to knock up a PCB which acted as a chassis too, though we'd still need to buy the motors and it would need some up-front time spent soldering it all together (it's a shame we don't have a load of soldering irons).
4. Yes :)

**Comment by AverageMarcus** [comment]
@spikeheap I'd be up for some pre-event soldering if needed. (I've got 2 soldering irons)

**Comment by spikeheap** [comment]
@AverageMarcus me too :+1: :+1:. Soldering could be good fun for people on the day so we could get attendees to do it, but I wonder if there's already enough going on to make just plugging things together than programming them enough. I'm up for some pre-event soldering too, maybe we could spread the word on meetup/twitter for a smallish gathering to knock them all.

**Comment by AverageMarcus** [comment]
@spikeheap Sounds like the prefect excuse for another BBQ to me.

**Comment by peterjwest** [comment]
I'm now free to come to this again, happy to bring another soldering iron along.

**Comment by spikeheap** [comment]
This event happened. It was awesome. Thanks everyone!
