### ISSUE TITLE
Full Stack Fest - September, 1–5 2015 Barcelona

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#122]
[![image](https://cloud.githubusercontent.com/assets/51385/8306722/338d887c-19b2-11e5-97d9-d17b6056b31e.png)](http://www.fullstackfest.com/)

[Full Stack Fest](http://www.fullstackfest.com/) - Barcelona Ruby Conference and Barcelona Future JS join forces on a single-track, weeklong event.

---

A few of us have tickets already:

* @spikeheap
* @peterjwest
* @benfoxall

---

Thought I'd raise an issue to help us organise anything like accommodation/travel.  If anyone else is interested in coming along - shout!

#### Outbound 
* BEN ✈️ **BA2049** 28th Aug 08:50 - LGW → BCN (11:55)
* RYAN 🚄 28th Aug: 09:17 St Pancras → Paris, 14:07 Paris → Barcelona Sants (20:33)
* PETE 🏇 28th Aug - LGW 14:45 → BCN 17:45

#### Inbound
* BEN ✈️ **BA2707** 6th Sept 10:30 - BCN → LGW (11:50)
* RYAN 🚄 6th Sept: 09:25 Barcelona Sants → Paris, 18:13 Paris -> London St Pancras (19:39)
* PETE 🏇6th Sept - BCN 06:45 → LGW 08:00

### Accommodation :house:

@spikeheap has booked [The Loft](https://www.airbnb.co.uk/rooms/5349403)

[![image](https://cloud.githubusercontent.com/assets/51385/9038774/d42b15ae-39ee-11e5-8976-e28eb6b57342.png)](https://www.airbnb.co.uk/rooms/5349403)

:dollar: 
* [x] @peterjwest to pay **£398**
* [x] @benfoxall to pay **£228**

### :white_check_mark: Check Lists

- [x] Ben arrived
- [x] Pete arrived
- [ ] Ryan arrived

**Comment by spikeheap** [comment]
I think @benfoxall is travelling business class on the way back. Just sayin'

**Comment by benfoxall** [comment]
The venue is [Auditorio AXA](https://goo.gl/maps/QF771) - so might be good to find a place near there

[![image](https://cloud.githubusercontent.com/assets/51385/8496047/21d265ca-216a-11e5-9e4e-9f0e9438d630.png)](https://goo.gl/maps/QF771)

**Comment by spikeheap** [comment]
I've added my travel arrangements, trains FTW

**Comment by benfoxall** [comment]
## Accommodation 

[Airbnb search](https://www.airbnb.co.uk/s/barcelona?checkin=28-08-2015&checkout=06-09-2015&guests=3&room_types%5B%5D=Entire+home%2Fapt&price_max=280&zoom=14&search_by_map=true&sw_lat=41.35454074051023&sw_lng=2.118710104916431&ne_lat=41.41209405021895&ne_lng=2.166775290463306&ss_id=1434361172087) for the times and dates

I think [THE LOFT/ DESIGN/ 190m2](https://www.airbnb.co.uk/rooms/5349403?checkin=28-08-2015&checkout=06-09-2015&guests=3&s=6uPC) is my favourite; it's got big windows and a bath. One of us would have to sleep on a couch I guess.  Slightly pricy - £1027.

Though also [SWEET DREAMS apartment - Entenca](https://www.airbnb.co.uk/rooms/4856177?checkin=28-08-2015&checkout=06-09-2015&guests=3&s=6uPC) would mean one of us would get to sleep in a shed! (shotgun). Cheaper - £911.

**Comment by spikeheap** [comment]
Good finds @benfoxall. The Loft (top option) gets my vote. It has 3 bedrooms, one's a single. 

@benfoxall you're in a hotel for the last half of the conference right? How would we split the costs? 1/3rds for the first few days and then 1/2 between me and @peterjwest for the remainder? 

I'm keen to get the accommodation sorted in the next couple of days. What's the next step?

**Comment by peterjwest** [comment]
I'd go with the cheapest one, that's a substantial amount of money for a bath.

**Comment by spikeheap** [comment]
@peterjwest those dates aren't available for the other two anymore. I had a quick look but couldn't see anything decent for much less than £1000.

**Comment by peterjwest** [comment]
Yeah okay then, go for the Loft.

**Comment by benfoxall** [comment]
## THE LOFT :100: :+1: :ok_hand:

Very cool; I just talked to @spikeheap, and he's going to take care of booking.  I've got a hotel room from 3-6 Sept - do you think anyone else would be interested in taking it for that time?

**Comment by peterjwest** [comment]
We could set up an airbnb account...

**Comment by spikeheap** [comment]
Right, we're booked into THE LOFT. It came to £1024. Good find @benfoxall  :+1:

**Comment by peterjwest** [comment]
Why didn't we go for the one with the swimming pool? https://www.airbnb.co.uk/rooms/4935444?checkin=28-08-2015&checkout=06-09-2015&guests=3&s=tYty

**Comment by peterjwest** [comment]
By my calculations me and Ryan have to pay £398
and Ben has to pay £228, does that sound right?

**Comment by spikeheap** [comment]
That sounds about right :+1:

**Comment by peterjwest** [comment]
Can we pay for this using the profits from Summer of Hacks?

**Comment by spikeheap** [comment]
Hi @peterjwest, I don't think that would be appropriate. There's loads of cool things we can reinvest any leftovers from the Summer of Hacks (if there is any... @benfoxall can comment on our balance to date), but I'm not really comfortable with it paying for us to go on a jaunt.

**Comment by peterjwest** [comment]
It was a joke. (Like we have profits)

**Comment by richdouglasevans** [comment]
> There's loads of cool things we can reinvest any leftovers from the Summer of Hacks

Dwarves please. Nothing would give me more pleasure than to careen down Snowdonia on a JS Oxford Adventure Bus crammed with a fistful of dwarves in various states of undress, a wild-haired @benfoxall cackling madly at the front wheel, and @AverageMarcus soldering himself to the front grill screaming _"Mair powa, hoots!"_

Have fun in Barca! Bonus points for tweeting your breakfasts.

**Comment by spikeheap** [comment]
This happened, and it was great.
