### ISSUE TITLE
FFConf November, 6th 2015, Brighton

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#123]
![image](https://cloud.githubusercontent.com/assets/51385/8674541/8455c8ca-2a36-11e5-8662-d88c435cd1e0.png)

Tickets are sold out.  Let me know if you managed to grab one and want to be part of our gang.

---

Gang so far:

* @skinofstars
* @rjmunro
* @benfoxall

**Comment by peterjwest** [comment]
Ah damn, I'm in Tenerife then.
