### ISSUE TITLE
Over The Air September, 25th & 26th 2015

### ISSUE THREAD

**Issue by AverageMarcus** [jsoxford/jsoxford.github.com#125]
http://overtheair.org/blog/

36 hours of mobile development

Price: **Free** - https://www.eventbrite.co.uk/e/over-the-air-2015-36-hours-of-mobile-development-registration-17678975291

I already have my ticket and @benfoxall said he's keen to go. Would be awesome to get a bunch of JS Oxford folk going.

**Comment by spikeheap** [comment]
Yeah I was really keen for that, unfortunately a really good friend is inconveniently getting married so I can't make it!

**Comment by AverageMarcus** [comment]
Does he/she want to get married in London? I hear St. John’s church in Hoxton is good! :wink:

**Comment by peterjwest** [comment]
I'm doing a Tough Mudder on the 26th, so probably not.

**Comment by benfoxall** [comment]
I've signed up!

**Comment by AverageMarcus** [comment]
:+1:
