### ISSUE TITLE
Add link to Youtube channel

### ISSUE THREAD

**Issue by AverageMarcus** [jsoxford/jsoxford.github.com#129]
Add a link along with our other social links to point to our awesome new youtube channel!

If possible it'd be pretty cool to add a banner to the top of the page when live streaming. (There's an API but doing it client side may be tricky)

**Comment by spikeheap** [comment]
:+1: :+1: :+1: :+1: :+1: , especially to showing the live stream on the site, that would be supercool

**Comment by AverageMarcus** [comment]
If I get a chance I'll see if I can do it. There is an API to find out the currently streaming videos its just getting that to work without a backend. (Perhaps a little heroku app we could use as a proxy)

**Comment by AverageMarcus** [comment]
Link has been added in #139. 
I attempted to work with the YouTube API but failed pretty bad. Not sure if anyone else wants to give this a go?
