### ISSUE TITLE
Ethical Engineering

### ISSUE THREAD

**Issue by choult** [jsoxford/jsoxford.github.com#130]
Our increasingly connected world, along with the promises of Big Data and Cloud Computing, offers us multitudes of opportunities to model the world and build powerful technology to improve not only the companies we work for but the lives of many. Yet far too often we, as engineers, focus on providing a solution to the problem at hand and overlook the problems that the solution itself might cause. In this talk, Christopher examines some of the issues our world throws up, and asks what it takes to engineer ethically.

**Comment by chrishoult** [comment]
Not sure if this is wholly clear that it's a talk submission, but it is ;)

**Comment by spikeheap** [comment]
Hi @chrishoult, I'd be excited to hear this talk, and it could work well in our September event (https://github.com/jsoxford/jsoxford.github.com/issues/97).

**Comment by chrishoult** [comment]
Hey @spikeheap I'm running PHP Berkshire that evening, I'm afraid - are you always third Wednesday? Or does it vary? Probably should have checked with @benfoxall the other day :)

**Comment by spikeheap** [comment]
Hey @chrishoult, no worries! We haven't pencilled in events post-September yet, but they vary, normally towards the middle of the month.

**Comment by spikeheap** [comment]
Hi @chrishoult, sorry for the looooong wait. We're putting together our October event for Wednesday 14th October. Are you free that evening, and are you still keen to give this talk? If it clashes with PHP Berkshire again let's coordinate and we can shift the date of our November or January talks to make things easier.

**Comment by chrishoult** [comment]
@spikeheap Thanks for getting back to me - unfortunately I've booked myself out to be in a show that night! Can we look at November or January? They're relatively free for me now - PHP Berkshire is the third Wednesday of every month.

**Comment by spikeheap** [comment]
Hi @chrishoult, no worries – we'll make it happen soon!

**Comment by benfoxall** [comment]
@choult thanks for this! It was great to get you along finally. #phptakeover
