### ISSUE TITLE
Web in the Woods - September 12th 2015

### ISSUE THREAD

**Issue by AverageMarcus** [jsoxford/jsoxford.github.com#162]
http://www.webinthewoods.co.uk/

> Web in the Woods
> Two days of camping and a day of amazing talks to instruct & inspire...

Price: £150 (+VAT) https://www.eventbrite.co.uk/e/web-in-the-woods-tickets-16200291508

If enough people want to go we might be able to get a discount: https://twitter.com/kris_jeary/status/631477394042449920

**Comment by AverageMarcus** [comment]
@spikeheap Did you say you were interested in this?

**Comment by spikeheap** [comment]
I did, I've just got to figure out how to get there after the Lead Developer conference (and whether I can afford it), but I'd be keen. If we can get a few together there might be discount too... let's spread the word.

**Comment by richdouglasevans** [comment]
I'd be up for it... but only if we can do a 10K run _together_ on the Sunday.

The [Oxford Half Marathon](http://oxfordhalf.co.uk/) will be 4 weeks away at the time of this conference and these moobs that I am fondling idly as I pen this need the iron discipline of no missed runs until then.

**Comment by AverageMarcus** [comment]
@spikeheap how are you getting to lead dev? London to Kent isn't too hard is it?

@richdouglasevans I cant run.

**Comment by spikeheap** [comment]
@richdouglasevans DEAL :+1: 

@AverageMarcus currently planning train into London – just thinking about the requisite camping things vs. the tube. We could share petrol for the way back though?

**Comment by AverageMarcus** [comment]
I was considering getting a hire car if enough people went (my car is a little unreliable right now) which means I could get a massive boot to take everyone's stuff.

**Comment by Thomas-PG-Attwood** [comment]
@AverageMarcus I'm definitely interested in this!

**Comment by AverageMarcus** [comment]
It's looking like I might not be able to afford this now. The [discount](https://twitter.com/kris_jeary/status/631477394042449920) wasn't as good as I'd thought it'd be and I've already said I'd go to [Over The Air](http://overtheair.org/blog/) (See #125)
