### ISSUE TITLE
Breaking Borders 18th Aug 2015

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#163]
http://breakingborde.rs, tickets are free.

I've been wanting to see Anna Dahlström talk for a while, and this looks pretty interesting. 

I don't mind driving if we can get a carful. I'll check about parking.

**Comment by AverageMarcus** [comment]
I'm going by :train:

**Comment by richdouglasevans** [comment]
Raincheck. I'm offskis on my hols at [your old stamping grounds](https://anicewalk.wordpress.com/2013/04/07/offas-dyke-september-2011-part-1/) Ryan. Have fun!

**Comment by spikeheap** [comment]
@richdouglasevans you're in for an amazing time... especially because according to the second picture in your link you're about to see 6-legged horses (at least I hope they're legs...)
![p1000436](https://cloud.githubusercontent.com/assets/464482/9269190/dbbd9f3a-425e-11e5-8e2a-10518a6ffe67.jpg)

**Comment by AverageMarcus** [comment]
@spikeheap Nah! That horse has evolved to have stirrups
