### ISSUE TITLE
Right pointing double triangle

### ISSUE THREAD

**Issue by iiSeymour** [jsoxford/jsoxford.github.com#164]
Bad emojis :cry: 

Unstyled page http://jsoxford.com/2015/right-pointing-double-triangle/

**Comment by spikeheap** [comment]
Good catch @iiSeymour. That post is also listed as being in the past, when it hasn't happened yet!

**Comment by spikeheap** [comment]
@AverageMarcus fixed our Meetup integration script so that page is now (catchily) http://jsoxford.com/2015/sun_with_face-end-fast_forward-loudspeaker-tropical_drink-tada-meat_on_bone-up-rocket-sweet_potato/. Maybe Seren's next JSOxford talk will be on the blight of emojis for accessibilty 😜.
