### ISSUE TITLE
2015-10-14 JS EVERYWHERE

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#167]
#### Theme (suggestion)

JavaScript is everywhere, so lets talk about some non-browsery ways things are getting exciting.

#### Date
Wednesday 14th October 2015, doors open 7:00pm, talks start at 7:30pm

#### Speakers

* **Electron** - [Richard Patching](https://twitter.com/disciplex)
* **Creating & Publishing Your First Node Module (In 10 Minutes)** - @richdouglasevans [@richdevans](https://twitter.com/richdevans)
* **TBA** - TBA

#### Core actions
- [x] Create meetup event
- [x] Confirm sponsorship for snacks/drinks (@spikeheap)
- [x] Confirm availability of White October (@benfoxall)
- [ ] Organise speakers

## Event organisation
- [ ] Ensure someone has carried out the actions above
- [x] Add to MeetUp.com (just prior to preceding event)
- [x] Announce event

**Comment by bigandy** [comment]
Is this event going ahead?

**Comment by spikeheap** [comment]
Hi @bigandy, it very much is. We're still after a third speaker, of course.

I'll get this up on Meetup today, thanks for the poke!

**Comment by bigandy** [comment]
Excellent, looking forward to it.

**Comment by richdouglasevans** [comment]
I just saw @benfoxall 's [tweet thing](https://twitter.com/benjaminbenben/status/649643035446394880) -- which is just like a tweet but with extra thing -- about talk descriptions for the uh, talks. Here's the description for my talk.

> Are you ready to level up with the Javascript Adventure Club? In this pulse-pounding demonstration of vi-rtuosity, a humble lumbercoder armed only with a copy of vim will test, develop, and publish a sweet module to npm in only 10 minutes. Your ticket to glory and riches is only an 'npm publish' away!

> * _#amazing_ :octopus: -- Agnes from Hull
> * _I learned a lot!_ -- Bill from Oxford
> * :star::star::star::star::star: -- Jambo79 from Stretford

Please do editorialize to suit.

**Comment by benfoxall** [comment]
Awesome, that's added now.

@patchfx - would you be able to add your talk description as a comment here?  You can see the rest of the meetup copy at http://www.meetup.com/JSOxford/events/225754855/ if it helps with length/style.

It's awesome if you can get it in before we announce (ideally by Monday).

**Comment by patchfx** [comment]
## Zero to MVP in 5 days with Electron
Learn how I scratched my own itch and shipped an MVP cross platform desktop app in 5 days. I'll be sharing my battles with Windows and how I struggled to the last hour to get installers and auto-updating in (plus my solutions). This talk contains lots of code, coffee, javascript, angular all wrapped up in electron. Essentially every tool a pretentious hipster would use if they were shipping an app.

**Comment by benfoxall** [comment]
@patchfx Brilliant! I've updated the meetup - sounds like a interesting talk; really stoked for this meetup!

@spikeheap announcing is all good by me.  I'll leave it to you to press the button in case you wanted to tweak any of the details. (cc/ @peterjwest)

**Comment by AverageMarcus** [comment]
@benfoxall I'm going to tweak the description *slightly* so the welcome page auto-grabs the speakers. Hope that's cool?

**Comment by benfoxall** [comment]
@AverageMarcus super cool :computer: :loudspeaker: :electric_plug:

**Comment by spikeheap** [comment]
__Announced__ ✨🎉🚀🍸💃🏽🏄. Descriptions look good :).

**Comment by peterjwest** [comment]
Very excited about this talk!

**Comment by spikeheap** [comment]
Done :+1:
