### ISSUE TITLE
Build a satellite September, 26-27th 2015

### ISSUE THREAD

**Issue by AverageMarcus** [jsoxford/jsoxford.github.com#168]
https://sa.catapult.org.uk/nanosat-weekend

We could build a satellite for free! 

@benfoxall wants one that you can tweet and it'll reply with where it is over the world

**Comment by richdouglasevans** [comment]
Truly we live in an age of marvels. I feel blessed and privileged.

I'd dig to participate in this. I'd also dig it if this could be an _official_ Javascript Adventure Club event. A proper one with lashings of ginger beer and tongue sandwiches to hand while we assemble a rocket ship to the moon!

How can I help to make this happen? (I will gladly sponsor _gratis_ umpteen kegs of ginger beer and dandelion and burdock too if that helps push this over the edge.

![To The Moon!](http://home.arcor.de/cybergoth/xype/tintinonthemoon_x.gif)
