### ISSUE TITLE
No Service

### ISSUE THREAD

**Issue by ukmadlz** [jsoxford/jsoxford.github.com#174]
No matter where you look in technology, everything has an online component. But with the advancement of web technologies and mobile apps, offline is becoming a key characteristic. This talk covers what's necessary to make a WebApp offline, and some nifty stuff to help along the way.

**Comment by richdouglasevans** [comment]
:+1:

**Comment by spikeheap** [comment]
Great talk @ukmadlz. Thanks for coming!
