### ISSUE TITLE
Port 80 All The Things Or At Least Most

### ISSUE THREAD

**Issue by ukmadlz** [jsoxford/jsoxford.github.com#175]
Micro service architecture is the in thing, and for good reason. With the growth of API's, distributed infrastructure and the amount of things that are becoming app centric it totally makes sense. I'll give an over view as to why I believe it's grown, why it's great and some handy ways of glueing micro services together. I will also point out some of the negative's and downfalls of this approach.

**Comment by AverageMarcus** [comment]
@ukmadlz Are you suggesting specifically port 80 (over 443)? :confused:

**Comment by richdouglasevans** [comment]
I have taken the talk title to be metaphoric with the thrust being services communicating over REST-ful HTTP as opposed to some custom socket+protocol.

**Comment by AverageMarcus** [comment]
@richdouglasevans I think you're right. It just irked me a little. Not sure if "REST-ful HTTP all the things" has as nice a ring! :stuck_out_tongue_winking_eye:

**Comment by ukmadlz** [comment]
@AverageMarcus why you so cruel? Trying to think of fun titles to boring topics is really hard. And Port 80/443 just doesn't look the same.

**Comment by AverageMarcus** [comment]
I'm not cruel, I'm just still terrified from Tim's talk on web security! :stuck_out_tongue_winking_eye: 
# "HTTP(s) ALL THE THINGS"

**Comment by ukmadlz** [comment]
Good point well made! But yes, can I haz talk?

**Comment by AverageMarcus** [comment]
When are you looking to give a talk?

**Comment by ukmadlz** [comment]
Do you have the dates for the Nov & Dec meetups?

**Comment by AverageMarcus** [comment]
I don't *think* we're having a Dec meetup. 

@benfoxall / @spikeheap - when is the Nov meetup and are there any slots?

**Comment by richdouglasevans** [comment]
> Trying to think of fun titles to boring topics is really hard. And Port 80/443 just doesn't look the same.

Take a :four_leaf_clover: from @benfoxall 's playbook for titles: emoji everything for instant fun :100: :star: :+1: 

:ship:80/443:8ball::bowtie::gift:

**Comment by benfoxall** [comment]
@ukmadlz Thanks **so much** for submitting the talk(s); both sound really interesting and like they'd go down very well at JSOxford.  Talk title/description is totally great as it is.

We've got meetups planned for November & January (people seem to get pretty busy in December).  @spikeheap is going to email you with particular dates and some more details about the meetups.

Again, thanks a lot for offering to speak at JSOxford! We're stoked to have you along.

:100: :star: :+1:

**Comment by benfoxall** [comment]
@ukmadlz also, we've got a [CFP for Render Conf](https://docs.google.com/a/whiteoctober.co.uk/forms/d/1dcDOEjlDpwmWs9GnzbBSGtQ2hKuHQ0SV08dhavL5bPw/viewform) open at the moment if you were interested in submitting your talks in there

**Comment by benfoxall** [comment]
Cleaning up github issues.  Thanks again @ukmadlz for giving this talk! (sorry we broke it)
