### ISSUE TITLE
Another attempt at doing Google Cardboard stuff with JavaScript 📦🚀

### ISSUE THREAD

**Issue by omgmog** [jsoxford/jsoxford.github.com#176]
That's not the title.

I'd like to give this another go, but probably not until the new year... watch this space!

**Comment by spikeheap** [comment]
Hi @omgmog, next year is cool, but the 18th of November could be cooler ;). I'll be creating a load of issues for the upcoming events shortly so we can get it all pencilled in.

**Comment by omgmog** [comment]
I'll see what I can do!

The first attempt was so smooth... it's hard to top that. http://www.tubechop.com/watch/7010590

**Comment by AverageMarcus** [comment]
:+1:

**Comment by omgmog** [comment]
## A _Walking_ Start at Google Cardboard with JavaScript
"A look at the technology we've got available to create Google Cardboard experiences using JavaScript, also sharks."

![](https://media.giphy.com/media/13bDCb1cEMWEMg/giphy.gif)

**Comment by benfoxall** [comment]
@omgmog would you be able to log this talk at https://github.com/jsoxford/events/issues

**Comment by omgmog** [comment]
Alright, done https://github.com/jsoxford/events/issues/1
