### ISSUE TITLE
November Talks 18/11/15

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#178]
#### Theme

TBA

#### Date
Wednesday 18th November 2015, doors open 7:00pm, talks start at 7:15pm

#### Speakers

* **20 Minutes into the Future with Google Cardboard and JavaScript** – Max Glenister #176 

> A look at the technology we've got available to create Google Cardboard experiences using JavaScript.

* **Digital Manuscript Toolkit – the journey so far** – Monica Messaggi Kaya

> An introduction to International Image Interoperability Framework (IIIF) and its use on the Digital Manuscript Toolkit (DMT) - where Monica is working specifically on a JavaScript client to edit manuscripts online (via browser).

* **OK Computer** - Peter Gasston

> In recent years there have been incredible advances in artificial intelligence and deep learning. As a result, powerful technology which used to be rare and expensive has very quickly become easily available and cheap. This will have both positive and negative consequences for web developers. In this talk I will look at how AI will change the development field, and provide techniques that will help designers and developers to work with AI to improve their skills and make better sites and applications for end users.

#### Core actions
- [x] Create meetup event & announce (@benfoxall)
- [x] Confirm sponsorship for snacks/drinks (@spikeheap)
- [x] Book The Story Museum  (@spikeheap)
- [x] Organise speakers (@benfoxall)

**Comment by AverageMarcus** [comment]
I think a service worker talk would go well here!

**Comment by benfoxall** [comment]
We've got the other two slots filled already (just waiting to confirm), though we'll definitely have more SW in the new year

**Comment by benfoxall** [comment]
Things to bring on the day:

- [ ] vga adaptor
- [ ] hdmi adaptor (think it's vga, but just in case)
- [ ] chromecast
- [ ] wifi hotspot
- [ ] ethernet cable
- [ ] clicker
- [ ] webcam
- [ ] tripod
- [ ] recording laptop (we probably won't cast this time)
- [ ] audio recorder
