### ISSUE TITLE
January Talks 20/01/16

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#179]
#### Theme

TBA

#### Date
Wednesday 20th January 2016, doors open 7:00pm, talks start at 7:30pm

#### Speakers

* **No Service** – Mike Elsmore (@ukmadlz) #174

> No matter where you look in technology, everything has an online component. But with the advancement of web technologies and mobile apps, offline is becoming a key characteristic. This talk covers what's necessary to make a WebApp offline, and some nifty stuff to help along the way.

* **TBA** - TBA
* **TBB** - TBB
* **TBC** - TBC

#### Core actions
- [ ] Create meetup event & announce
- [ ] Confirm sponsorship for snacks/drinks (@spikeheap)
- [ ] Book The Story Museum  (@spikeheap)
- [ ] Organise speakers

**Comment by spikeheap** [comment]
This event has been postponed until Feb...

**Comment by AverageMarcus** [comment]
@spikeheap Will this one be instead of the Feb social or are we skipping this?

**Comment by spikeheap** [comment]
Hi @averagemarcus, @benfoxall is putting together Feb because I'm away for a month with rubbish connectivity, but I think the plan is to run talks in Feb. Watch this space!

**Comment by AverageMarcus** [comment]
:+1:
