### ISSUE TITLE
February Meetup 17/02/16

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#180]
#### Date
Wednesday 17th February 2016, doors open 7:00pm

#### Core actions
- [x] Confirm booking at Story Museum (@peterjwest)
- [x] Create meetup event & announce (@benfoxall)
- [ ] Confirm sponsorship for snacks/drinks (@spikeheap)

**Comment by benfoxall** [comment]
talks:
* No service - #174
* Show and tell
* [talk wanted]

**Comment by benfoxall** [comment]
[Scheduled on meetup](http://www.meetup.com/JSOxford/events/228604759/), but not announced.

We can hit the announce button this afternoon - if anyone spots any mistakes/errors then shout

**Comment by peterjwest** [comment]
Show and tell - do we want a time limit to prevent rambling?

**Comment by tomlane** [comment]
A set amount of time and an alarm / shine a light at them to say time is up? Seen that somewhere before.

**Comment by AverageMarcus** [comment]
OGN has a countdown clock projected

**Comment by peterjwest** [comment]
I say we get a bank of floodlights for if they're over time, or maybe that pain ray the US military made.

**Comment by spikeheap** [comment]
This happened, and I really enjoyed it. Thanks everyone for everything.
