### ISSUE TITLE
move from gitter to slack

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#187]
We're thinking of moving our "official chat" from [gitter](https://gitter.im/) to [slack](https://slack.com/).

Would love to hear feedback on this - please add any comments/thoughts here.  We've put out a [twitter poll](https://twitter.com/JSOxford/status/661227564770439168) too.

### reasons to move

* we've had issues with gitter clients in the past
* noisy chat (multiple channels would help)
* notifications/emails seem to stack up with gitter
* a few of us are using slack anyway, so it could be handy to have jsoxford in the same app
* @danielthepope has a slack sticker on his laptop, this would [give the sticker meaning](https://gitter.im/jsoxford/jsoxford.github.com?at=56379b9a3003682f1408be09)

### reasons not to move

* gitter is more open (visible without login + [embed options](https://sidecar.gitter.im))
* keeps us close to github
* @omgmog doesn't have [a slack sticker](https://gitter.im/jsoxford/jsoxford.github.com?at=5637b386aefcbd6411ee1746)
* m*a*rk**do**w`n`

---

- [x] move @jsoxbot over
- [x] update main site
- [x] hook up signup page - [jsoxford.herokuapp.com](http://jsoxford.herokuapp.com)

**Comment by spikeheap** [comment]
:+1: to moving, I've had plenty of issues with the clients in the past, and am pretty fed up of being inundated with notifications on my phone. Slack seems to handle that really nicely.

**Comment by AverageMarcus** [comment]
:+1: im already using slack with 3 teams so have it open all the time

**Comment by garrettc** [comment]
+1 from me. I find the notification handling in Slack so much better.

**Comment by omgmog** [comment]
:+1: 

![](https://media.giphy.com/media/qvdqF0PGFPfyg/giphy.gif)

**Comment by Rumyra** [comment]
Slack all the things :+1: (But proximity to Oxford probably discounts that vote ;) )

Also https://github.com/rauchg/slackin - we were looking at this for easy sign up for users (slack default is invite only and can be a pain for generally public slacks) - I believe Front End London use it successfully...

Also I nearly typed pubic (tehehe)

**Comment by sstarr** [comment]
@Rumyra Thanks for the slackin reminder! I've been meaning to set that up for ages.

If anyone fancies giving Slack a try then you're welcome to join us at @BathRuby here: https://bathruby-for-slackers.herokuapp.com

And if you come along to witness Ruth's VJing at [Wednesday night's meetup](http://www.meetup.com/bathruby/events/226315878/) then I have one spare Slack sticker left over which is free to whoever claims it first :)

**Comment by benfoxall** [comment]
twitter poll results so far:

![image](https://cloud.githubusercontent.com/assets/51385/10906112/d635ebb0-8216-11e5-8b3c-7e2fb5bcda19.png)

**Comment by AverageMarcus** [comment]
Does it tell you who voted for what? It'd be good to hear why those 7% want to keep Gitter.

**Comment by omgmog** [comment]
The polls on Twitter are pretty useless, no analytics available, and you have to go and find your poll once it's over as it's not promoted anywhere.

Also perhaps some useful links for anybody in that 7% (which is 1 person in this small number of voters):
- https://slack.com/is
- http://theslackguide.com/
- https://www.youtube.com/watch?v=B6zVzWU95Sw

And they seem to do handle better than Gitter!

**Comment by AverageMarcus** [comment]
I just wish Slack used markdown :disappointed:

**Comment by benfoxall** [comment]
@omgmog great links! @AverageMarcus I've added that to the list.

It all sounds very happy towards Slack then.

## :100: :palm_tree:  LET'S DO THIS :rocket: :guitar: :sparkles: 

We've actually had a [slack team](jsoxford.slack.com) up for a while to try it out. And @peterjwest has already set up slackin (thanks for the input @Rumyra & @sstarr), so JOIN NOW AT:

# https://jsoxford-slack.herokuapp.com

We'll keep this issue open till we've checked all the boxes (hooking in @jsoxbot for example)

If there's anything else we need to do add it to this issue

**Comment by benfoxall** [comment]
## UPDATED LINK

# https://jsoxford.herokuapp.com/

**Comment by omgmog** [comment]
So how about that @jsoxbot integration https://jsoxford.slack.com/services/new/hubot

**Comment by AverageMarcus** [comment]
@omgmog I'm on it!

**Comment by AverageMarcus** [comment]
Final item on the list: https://github.com/jsoxford/jsoxford.github.com/pull/188
