### ISSUE TITLE
Meetup date changes

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#192]
Dates I'd like to change (separate issue to make sure we've mirrored this with the story museum or others):

- [x] January 20 -> February 17th #179 
@spikeheap will be skiing, I'm not sure where I'll be

- [x] March 16th -> March 23rd #181 (optional)
I'll be away (though cool if @spikeheap & @peterjwest would like to take it)

**Comment by spikeheap** [comment]
:+1:

**Comment by AverageMarcus** [comment]
Does this mean no JSOxford for 2 whole months?! I don't know if I could cope!

**Comment by omgmog** [comment]
We could hold a secret online-only JSOxford in January

**Comment by spikeheap** [comment]
I like the idea of that @omgmog, that way I could join from Italy and not get "I'm missing JSOxford sad face" :+1:

**Comment by spikeheap** [comment]
I've emailed the Story Museum about the new dates to check availability

**Comment by omgmog** [comment]
> I like the idea of that @omgmog, that way I could join from Italy and not get "I'm missing JSOxford sad face" :+1:

We could do something cool like this:

![](https://media.giphy.com/media/XJhHnTKwTcgfe/giphy.gif)

Each person can have a 3d avatar (threejs) with their face (via getusermedia) and we can have a virtual venue (webrtc).

WHO WANTS TO HACK ON THIS IDEA WITH ME?

**Comment by spikeheap** [comment]
:+1: I can provide manpower, though I've not used threejs before.

**Comment by AverageMarcus** [comment]
I'm **SO** on this!

**Comment by peterjwest** [comment]
Looks awesome! I can help

**Comment by omgmog** [comment]
watch this space :arrow_right: https://github.com/omgmog/Tele-JS :arrow_left:
