### ISSUE TITLE
Javascript Story Time Retro

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#193]
Would be awesome to capture any issues or suggestions to make things better/smoother/awesome-er in the future.  Add comments here, and I'll update the main issue.

## stuff

* no water for speakers
* only coke (?) as soft drinks
* no bottle openers
* lighting wasn't perfect
* we didn't have any questions
* wifi was shakey (especially bad for presentations)
* no time for questions
* slack highlights didn't work very well
* we didn't know the projector resolutions to tell speakers
* dark slides didn't work very well
* people found it hard to find
* not enough time to socialise with each other
* spotlights pointing at the screen made it hard to read
* the microphone position might be bad
* slides hard to make out in video
* It was a pain to drop off drinks - we could have driven into the square to make it easier
* No time from questions
* Felt rushed

## Actions

* make sure we have water and soft drinks available
* work out projector resolution & give tips on the projector (dark animations are hard to make out)
* mobile speaker hotspot? (does anyone know which mobile networks had good reception)
* provide a map or better directions
* limit to 2 long talks, or 3 short talks
* buy bottle openers
* work out lighting arrangements, write down
* find a JSOxford bag - @benfoxall

**Comment by MarcusNoble** [comment]
(There was cans of coke)

* A microphone wouldn't go amiss. 
* Some sort of "This way to JSOxford" sign could be useful.

**Comment by AverageMarcus** [comment]
(There was cans of coke)

* A microphone wouldn't go amiss. 
* Some sort of "This way to JSOxford" sign could be useful.

**Comment by garrettc** [comment]
More time for socialising (or to badger speakers) in-between talks would be good. It felt a little rushed last night.

**Comment by omgmog** [comment]
I think it being a new venue, meant that some of the organisation ended up being ad-hoc (music for example) and the slack highlights was definitely a rush (I put the slides together 20 mins before...)

I think it was a cool venue, and a very cool space, but yes lighting wasn't perfect -- I think the biggest issue was the spotlights pointing at where we were projecting. So some control over that in the future would be good.

I'm still unsure what resolution the projector was! My slides were made on massive and/or retina screens, but heavily tested with a device emulator at 1024x768, but they looked different even still on the projector.

My second webaudio demo slide was super dark, and so yes not great on the projector..

![](https://i.imgur.com/jBli2r5.jpg)

Remains to be seen (or heard rather!) but Jenny (who works in video) suggested that the mic would have been better placed on the podium, as it will just pick up the sound of walking around at the front from where it was positioned.

With regards to ease of finding the place, I think some signs (maybe from G&Ds) towards the entrance and such would be useful if we're there again. 

Or having a description of how to get there...

> Go down St. Aldates, turn right at G&D's and it will be on your right

Or having somebody to greet/see people in until the start of the talks.

**Comment by AverageMarcus** [comment]
On the topic of providing a map...

How about a Google Streetview powered Google Cardboard directions website?

**Comment by omgmog** [comment]
> How about a Google Streetview powered Google Cardboard directions website?

I... I could make this, but first I've got to take https://jscard.xyz beyond MVP :shipit:

**Comment by AverageMarcus** [comment]
Do it! It'd be SO cool!

**Comment by benfoxall** [comment]
Hey, thanks a lot for the comments - I've pushed some of them into the main issue text.

**Comment by benfoxall** [comment]
From @spikeheap:

It was a pain to drop off drinks - we could have driven into the square to make it easier
No time from questions
