### ISSUE TITLE
JSOxford.next

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#197]
We’re planning a new version of the JSOxford site, this is going to be next.jsoxford.com, we’ll develop it alongside the current site and hopefully change over early next year.
# Why
- **To switch to a new publishing approach** - @spikeheap is working on a new structure for publishing events driven by jsoxford/events - this will be the central source of meetup data, so we want to switch to using that to generate our source rather than mixing in content from meetup and our jsoxford repo.
- **Complexity** - the current site has quite a complex front-end structure (215req, 3.4mb, 30s initial load) - which we can’t solve by adding stuff. Also the complexity of our templates and build tools make it hard for us to make changes and get new people up to speed with it.
- **Missing (or hidden) features and content** - things like how to join, how to get there, how long we’ve been going, how to get in touch aren’t clear for new visitors
- **New brand** - we’re (still) working on the updated logo and branding feel,  this gives us an opportunity to push things forward.
# What

We’re going to create a new site from the ground up - with an aim of simplicity and focus on visitor needs.

The design is going to be very different from the current one (especially when we get the new logo dialed), for now we’re going to just focus on the content and make sure we’ve got everything we need on the pages before thinking too much about the look of it.
# How

**Publicly** - everything will be open on github or in slack.  Our first step will be to create a simple set of objectives and architecture goals for the site, then we’ll branch from the current site and start fresh.

**Slowly** - this depends on the new events thing, and a new logo/look - we’re going to make sure those are badass rather than building hacks in our site.

If people are interested in helping out, add a comment to this ticket to say and we’ll make a team or whatever.
# When

There isn’t going to be a set “launch” date - it’ll run alongside the current site, and we’ll switch over when it’s ready.  (We’ll aim for around February/March time though.)
# The current site

We’ll always keep the current site live somewhere (it’s static!) - though we’re going to have a soft feature freeze going on from here.  You can totally add stuff, or improve things though a) they might not make it to the new site and b) you could totally be getting involved in the next version.

**Comment by omgmog** [comment]
Happy to help with any front-end/UX stuff :+1:

**Comment by AverageMarcus** [comment]
Count me in! :+1:

**Comment by benfoxall** [comment]
@omgmog @AverageMarcus Ace! Welcome to the @jsoxford/jsoxford-next club

**Comment by henrahmagix** [comment]
And me please!

**Comment by omgmog** [comment]
Work has been happening in #234 so this will be closed
