### ISSUE TITLE
Better recording/streaming

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#201]
The recording quality was pretty low in the past, would be good to get some better hardware (lapel mic, vga video capture).

If anyone has some particular suggestions, please comment

**Comment by omgmog** [comment]
Words from my wife Jenny who is in the "filming events" biz:

> The microphone you've got should be fine, it's just not close enough to the speakers mouths.
>
> Try attaching the microphone to the podium so that it's closer to the speakers mouths and won't get knocked by their feet.
> 
> Alternatively, there are some lapel mic's available that can just be plugged into a smartphone, which could work nicely as a cheap lapel mic solution -- but they're not always amazing quality, and might have a background hiss.
>
> With the video, the hardware is fine, but I would personally have a shot on a tripod from behind the audience -- this would allow you to capture audience participation, such as hand raising, etc. (and it's probably a bit more flattering angle of the speaker!)

![](https://media.giphy.com/media/13py6c5BSnBkic/giphy.gif)

**Comment by rjmunro** [comment]
What recording quality are you talking about? Do you mean the YouTube hang outs on air live steam stuff, or something else?

**Comment by AverageMarcus** [comment]
I would go for a lapel mic than one fixed on the podium as we've had a lot of people that walk around while giving talks.
