### ISSUE TITLE
Summer of Hacks 2016

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#204]
Following on from last year's pretty amazing (if we do say so ourselves) Summer of Hacks, we need to run it again. 

We fear change, so most of the hack days will have the following in common:
- They're free!
- Use the same code of conduct
- Use the same venue
- Use the same catering options (pastries and 🌯🌯🌯),obviously catering for any special dietary requirements
- Start at 10am
- End around 5pm

We'll create issues for each of the days. This issue is to sort out overarching admin. 

Last year we got in touch with the universities and a couple of other groups to try to increase the diversity of our events. We want to do better this year.
#### Food and snacks
- Tea
- Coffee
- Coke
- Diet coke
- Sprite
- Diet sprite
- Fruit juices
- Water
- Crisps
- Tortillas
- Bananas
- Oranges
- Apples
- Grapes
- Beers
#### Initial admin (we can break these out into individual issues as needed):
- [ ] Secure/confirm sponsorship
- [x] Decide on a venue
- [x] Book venue
- [ ] Publicise CoC on summerofhacks.io
- [ ] Figure out catering requirements (morning, lunch and snacks/fruit/drinks)

**Comment by omgmog** [comment]
This totally happened.
