### ISSUE TITLE
2016-07-23 Summer of Hacks #2: Game Dev Day

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#207]
Game Dev Day is a hack day for people to have fun making games and virtual reality experiences in web technologies.

#### What is a hack day?

A hack day is an event where people come together to collaborate on interesting ideas and learn new technologies. People usually organise themselves into teams, work on a project and then demo it at the end of the day. Hack days work best when there's a relaxed, open and friendly atmosphere. 

#### Who is this event for?

Anyone who is interested in games or VR is welcome.
If you can write code or draw pictures, that's a bonus!

#### What technologies are we using?

We will be focussing on web technologies: HTML and Javascript.

We'll have mentors who can help with libraries such as:
- ThreeJS (3D scenes in javascript)
- AFrame (Simple VR experiences)
- Phaser (Game making framework)

We'll have beginner tutorials & example projects for these technologies, to get you started.

Feel free to try other tools and technologies, we will help wherever we can!

#### What does the day look like?

- 09:30 Arrive, drink coffee and eat pastries
- 10:00 Intro to the tech
- 10:15 Discuss ideas and form teams
- 10:45 Start hacking
- 13:00 Lunch break!
- 17:00 Demos
- 17:30 Finish up and head to bar/cafe for post-event celebrations

When we get set up you'll have the chance to pair up with another attendee or embark on a workshop on your own. We'll have mentors on-hand to help if you get stuck or give you suggestions on workshops you might like.

##### Food

We'll be providing pastries from a local patisserie, and a burrito lunch. You'll get to build your own burrito/box. We'll also have a selection of fruits and snacks, teas and coffees.

If you have any concerns about dietary requirements (or any questions whatsoever) get in touch.

#### I have a question

Great! You can reach out to any of the JSOxford organisers:

- [Pete West](https://twitter.com/peterjwest), 07565631681
- [Max Glenister](https://twitter.com/omgmog)
- [Ryan Brooks](mailto:ryan@slatehorse.com), 07841757984
- [Ben Foxall](https://twitter.com/benjaminbenben)

#### What will I need?

- You'll need a laptop and charger. If you don't have access to a laptop let us know and we'll do our best to sort you out.
- Bring your smartphone for VR or to use as a controller.
- Also, bring a VR headset if you have one!

#### Date

Saturday 23rd July 2016, 10:00 to 17:00

#### Organisation

- [x] Book venue
- [x] Flesh out description for the day (above) (@peterjwest)
- [ ] Invoice sponsors
- [x] Add to Meetup.com
- [x] Add to SummerOfHacks.io
- [x] Book pastries
- [ ] Purchase snacks/drinks (see #204)

#### On the day

- [ ] Take a group photo
- [ ] Record a very short video summary of the day

Part of the Summer of Hacks 2015 (#204).

**Comment by omgmog** [comment]
There's a microsite coming together on http://gamedevday.club/, source on https://github.com/omgmog/gamedevday.club

**Comment by benfoxall** [comment]
@omgmog that. is. amazing. I've got a few more tweaks to make to the SoH site, though will totally link it over to that microsite

**Comment by peterjwest** [comment]
I've updated Meetup and added you as an organiser @omgmog.

Also, I might have a friend who would be willing to be a Unity -> JS mentor.

**Comment by omgmog** [comment]
:100: awesome, and the more help the merrier.

Some todos in prep for the day:

- [ ] Some independent promo tweets for the hack day (other than the tweets from JSOxford!)
    - HYPE :boom:
- [ ] Come up with some intros for Phaser and A-frame
- [ ] Come up with some basic support packs for Phaser and A-frame, including:
    - links to documentation
    - some tutorials (existing)
    - some generic resources/assets, appropriate for the theme ***
- [ ] *** decide on a theme, to direct the projects a bit?

**Comment by Rumyra** [comment]
Did someone email Belen back? @peterjwest ? I can't remember who said they would...

**Comment by peterjwest** [comment]
I thought you emailed her my address? I don't have hers.

**Comment by Rumyra** [comment]
Balls I can't find it - did I slack it to you...

Just jumping on a flight - I WILL SEE PEOPLE IN REAL LIFE TOMORROW. This is exciting and we can figure it out then 🤓 :mlphappy:

**Comment by AverageMarcus** [comment]
Looks like @omgmog needs to get a job at GitHub so he can implement mlp emoji!

**Comment by omgmog** [comment]
![](https://github.com/omgmog/digitaloxford-slack-emojis/blob/master/emoji/mlphappyluna.png?raw=true)

**Comment by omgmog** [comment]
For Saturday, some VR game ideas that I've been writing down this past month or so...

- 3D Pong (Multiplayer using Pusher perhaps)
- Emoji shooter (like Duck Hunt, but using gaze/reticle to target)
- Basketball hoop shooting
- Ring toss game with different size rings/distance of sticks, etc. Could also be multiplayer
- Multiplayer exploration. Represent other players and show where they're looking.
- Whack-a-mole (again using gaze/reticle)
- Escape the room/mystery game. Lots of interaction might make this hard though
- 3D Where's Wally type game
- [My "line finder" game](https://blog.omgmog.net/line-finder/) but rendered using 3D primitives 
- Bird on a line game, must poop on passing pedestrians. Not sure how you would handle the input for move left/right and poop. Could use gamepad.
- Sniper game, where you are given clues over time to find the target. A bit like "Guess Who". Points for speed/accuracy
- Falling from a plane simulator -- try and slow your descent, e.g. birds/clouds/passing planes
- Multiplayer FPS where your health is your ammo, so you have to shoot carefully.

From the Meetup page, others have added...

*Alex Addams*: 
- Treasure Walker: Track users location as they walk around an area, collect treasures contained in shape drawn.
- It Happened When?: Digital version of timeline, dropping historical events into a timeline trying to get it in the right place
- ScribblePath: Players given an image and instructions what to connect/draw lines through on central monitor. Have to draw paths on blank mobile screen that match to score points

*Rich*:
- SuchInvaders: words drop down from the top of the screen, shoot only those words that are voiced dental fricatives.

**Comment by gfwilliams** [comment]
More ideas:

* A version of 'Death Run 3D' [link](http://www.y8.com/games/death_run_3d) without ads and in VR would be amazing - and hopefully not too hard technically.
* A 'PCB layout' puzzle game would be fun (but not VR). Very simple rules, but it can be quite challenging and fun.
* A [LiquidFun](http://google.github.io/liquidfun/)-based water physics puzzle game
* A friend did a multiplayer 3D tank game that'd be great in WebGL and/or VR. The tanks were just cubes and moved over a hilly terrain. They were slow to manouver but you could aim quickly and fire projectiles. Something about the slow inevitability of seeing a projectile flying towards you made it really fun.

**Comment by MarcusNoble** [comment]
I really want to have a stab at a Pokemon Go style game that uses your location to unlock things.

**Comment by peterjwest** [comment]
Lots of great ideas! 

Just remember that the spirit of a hack day is to collaborate with other people and come up with ideas together. We'll have time at the beginning for brainstorming ideas and forming teams.

**Comment by Rumyra** [comment]
I think I'm going to try and build Chuckie Egg in JavaScript, maybe with Phaser

That is all 🐣

**Comment by adam-thomas** [comment]
Imagine a VR version of the first stage from Spore, where you're moving around fighting/absorbing other organisms and growing bigger.  The change in perception as you grow larger could be really cool in VR.

**Comment by omgmog** [comment]
This happened, it was awesome. We had 23 attendees (out of an expected 30) so a great turn out.

Retro in #225 to collect feedback!

/beingryan
