### ISSUE TITLE
2016-09-17 Summer of Hacks #4: Hardware

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#209]
This is a day of hacking on hardware. We'll have some interesting kits to play with and you're welcome to bring any additional hardware or things you'd like to hack.

This event follows the standard Summer of Hacks format (#204)
#### Who is this event for?

Anyone interested in learning a bit about hardware. There are no minimum entry requirements, other than an inquisitive mind. If you've never touched a breadboard before, that's fine – we have some starter kits and plenty of helpful people to guide you. If you're a bit more experienced that's great too, as you'll get to play with some new kit or hack on a project with like-minded people.
#### What does the day look like?
- 09:30 Arrive, drink coffee and eat pastries
- 10:00 We'll get started
- 13:00 Lunch! 
- 16:30 Retro. We'll have a show and tell for those that want to, and reflect on the day
- 17:00 Finish up and head to bar/cafe for post-event celebrations

The day is free-form, and you'll be hardware hacking in pairs or small groups.
##### Food

We'll be providing pastries from a local patisserie, and a burrito lunch. You'll get to build your own burrito/box. We'll also have a selection of fruits and snacks, teas and coffees.

If you have any concerns about dietary requirements (or any questions whatsoever) get in touch.
#### What isn't this event?

This isn't a competition, race or hackathon. There will be no prizes, other than basking in your own glory as you learn new things, meet new people, and have a good time. 
#### I have a question

Great! You can reach out to any of the JSOxford organisers:
- [Ryan Brooks](mailto:ryan@slatehorse.com), 07841757984
- [Ben Foxall](https://twitter.com/benjaminbenben), 07540838982
- [Pete West](https://twitter.com/peterjwest)
#### What will I need?

You'll probably want a laptop and charger (or a swanky laptop that'll last the day). If you don't have access to a laptop (or a friend you can drag along with one), let us know and we'll do our best to sort you out. 

If you have any tools or components and would like to bring them along, please do. We'd recommend marking them up somehow so it's easy to check you're taking the right things home.
#### Date

Saturday 17th September 2016, 10:00 to 17:00
#### Organisation
- [ ] Flesh out the description above, once we've expanded the project a little
- [ ] Invoice sponsors
- [ ] Find additional sponsor for hardware
- [x] Book venue
- [x] Add to Meetup.com
- [x] Add to SummerOfHacks.io
- [ ] Book pastries
- [ ] Purchase snacks/drinks (see #204)
- [ ] Find/write up beginners track
#### On the day
- [ ] Take a group photo
- [ ] Record a very short video summary of the day
#### Additional hardware sponsorship

We're aiming for ~30 attendees, working in pairs, so 15 kits. We'll flesh out the kit contents shortly, but a rough estimate suggests ~£35+VAT per kit would allow us to procure WiFi Espruinos and a good selection of sensors and fun things.

Part of the Summer of Hacks 2015 (#204).

**Comment by gfwilliams** [comment]
Just some ideas (not necessarily robots - but microcontrollers):

* Breadboard robots - continuous rotation servos stuck to breadboard - similar to last time, but without the nasty soldering, and less sensors. Realistically you'd be looking at light following, and potentially navigating a maze.
* Hack a toy 1 - fluffy toys, microcontroller, vibration sensor, speaker, lights, and then hack the toys to do different things (speech, lit eyes, etc.)
* Hack a toy 2 - RC cars - could hook up to servo motors of cars and could do turn indicators, brake, reverse, sounds, etc. Maybe too expensive unless people have their own cars?
* Handheld games - Even with just breadboard you could have digital dice (where you get to play with a 7 segment LED) or could slap an LCD/OLED and some buttons on there and do snake, tetris, breakout, etc.
* Lighting - individually addressable LED strips, some cheap IKEA lights and phone chargers, and people could make their own mood lighting.
* Pimp my box - could take a standard wooden box and add interior lighting, sound, music, etc.

**Comment by benfoxall** [comment]
Can/should we change the name of this?  Maybe to something more generally covering hardware, rather than robot specific?

I guess themes/words: hardware, electronics, physical, practical, tools, build, make

Some possibilities: hardware hack, hwjs, hardware day, maker hack, build, …

**Comment by Rumyra** [comment]
Thoughts after talking today:

Project with screen - we'll be doing this at Fullstack - mostly along the lines of games by the looks.

So buttons/joypad, or something physical like the wire and loop game.

Be nice to have a beginners track too - but I'll have a think whilst I play with the screen.

**Comment by gfwilliams** [comment]
Stuff I need to bring on the day:

* 15 Espruino kits
* Solid core wire
* Strippers, wire cutters
* Soldering iron, solder, solder sucker & third hand
* Some VGA Cables (and VGA monitor?) if someone wants to play with VGA out, IR remote controls and receivers for those interested in doing more complicated stuff
* Shim kits?

anything else?

And Ryan's going to bring some of the other bits and bobs he ordered, and maybe some of the stuff from the Robots hack day?
