### ISSUE TITLE
Planning events for 2016

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#210]
Rather than keeping this in my notebook, let's plan this here.

With May sorted we need to get the rest of the year in the calendar. A rough plan could be:
- 18th May
- 15th June
- 20th July
- 10th August
- 14th September
- 19th October
- 16th November
- Nothing in December

We may want to consider swapping out August or September for a social (in St Aldates?) to reduce the burden as super-secret-not-so-secret conf stuff gets closer.

This issue covers:
- [ ] Creating the events as issues
- [ ] Confirming sponsorship for the events
- [ ] Booking the events in bulk with the Story Museum

**Comment by benfoxall** [comment]
# 🎊 🎆 👍 💯 ❤️
