### ISSUE TITLE
June Talks 15/06/2016

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#211]
#### MOAR JavaScript

This month we'll be all about the JavaScript, with an introduction to service workers and another chance for you to show off something cool.  

There will be talks, drinks, people, and tonnes of fun.

http://www.meetup.com/JSOxford/events/231241768/

#### Date
Wednesday 15th June 2016, doors open 7:00pm, talks start at 7:15pm

##### An Introduction to Service Workers – Phil Nash

Service Workers are the biggest thing to hit the browser since XMLHttpRequest. We'll take a look at what the Service Worker can do for your app and more importantly, your users. We'll see the surprisingly small amount of code you need to get started with a Service Worker and finally we'll take a look at Progressive Web Apps and how the Service Worker will take part in a revolution for web applications.

##### Javascript from Scratch – Ashok Menon (@amnn)

WARNING: This talk features dangerous levels of impracticality.

Have you ever wondered how far you could get if all you had were functions? Probably not, you have better things to do with your time, but fear not, I don't. Join me on an adventure as we rebuild familiar concepts like booleans, if expressions, numbers, pairs, and lists, from functions alone.

##### Speaker Bio

Ashok is a computer scientist who sometimes pretends to be a software engineer. He likes functional programming, type theory and long walks on the beach, and dislikes the misappropriation of mathematical terms (I'm looking at you, "isomorphic" javascript). He also still believes people (deep, deep down) want to use mathematical proofs in industry, so nobody break his bubble. 

#### Show and Tell – Everyone!

May's show and tell had an amazing collection of side-projects, and we want to hear about yours. It doesn't need to be pure-JS, we want to know about that thing you're hacking on or thinking about.

We’ll have signup details closer to the time, for now - have a think of something you’d like to share. 

#### Core actions
- [x] Create meetup event & announce
- [ ] Confirm sponsorship for snacks/drinks (@spikeheap)
- [x] Book The Story Museum  (@spikeheap)
- [x] Organise speakers (@benfoxall)

#### Packing list
- [x] camera (@spikeheap)
- [ ] microphone (@peterjwest)
- [x] clicker (@benfoxall)
- [ ] tripod (?)

**Comment by benfoxall** [comment]
## Retro.

Rather than creating another ticket, shall we add any comments in here? Seems like it might keep things nicely together /@spikeheap

**Comment by benfoxall** [comment]
* I was happy that we made a point of welcoming new people and pointing them at Dan & Marcus (even though they didn't get any chats).  I'd really like to get feedback from some of the new attendees
* it was harder to get show and tellers this month, though I liked it being a bit more haphazard. Props to Matei for coming forward late one.
(more to come, but going underground)

**Comment by MarcusNoble** [comment]
I really enjoyed the "Show & Ask". Might be hard to keep it going though.

**Comment by AverageMarcus** [comment]
I really enjoyed the "Show & Ask". Might be hard to keep it going though.

**Comment by danielthepope** [comment]
Slightly disappointed at the lack of laser horse stickers, but hey ho. It felt like I had less time to chat to people, but that might have been because of the spontaneous camera duty. I'll try to talk to more people at the next one!

**Comment by AverageMarcus** [comment]
@danielthepope I do have one save for you. Just forgot to bring it 😛

**Comment by danielthepope** [comment]
Well, my concern was laser horse stickers for the other attendees - I've got one on my laptop already (and a spare for my new laptop whenever I finally get round to buying it)

**Comment by spikeheap** [comment]
- The A/V was a bit haphazard because we lost the film crew at the last minute, but it came out okay in the end. To do more of it ourselves we should really get some lavalier mics (researching on the internet makes the difference in sound quality obvious). Thanks to Dan for stepping up and filming.
- Collecting the different recorded streams is/was a bit a of a faff. The show and tell clips were much easier to get online because it was all recorded on the one device.
- Show and tell was good fun again.
- Show and ask was awesome.
- Getting there at 6:30 to set up made it feel much less rushed, though I need to remember to take the "not this way" sign off the door when I arrive next time.
- Newbies. It was great to see so many new faces, and it felt like everyone made everyone else feel welcome. I like the way the events feel at the moment.
- We should have brought the stickers.
- A signpost would still be useful to help first timers find the place.

**Comment by peterjwest** [comment]
Sorry about the stickers, I had them and couldn't come :(
