### ISSUE TITLE
September Talks 28/09/2016

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#213]
#### Theme

September

#### Date
Wednesday 28th September 2016, doors open 7:00pm, talks start at 7:15pm

#### Speakers

* **OWASP Top 10 Proactive Controls 2016** - Katy Anton #228 
* **Show & Tell** - Everyone #227
* **Ethical Engineering** - Chris Hoult #130

#### Core actions
- [x] Create meetup event & announce
- [x] Confirm sponsorship for snacks/drinks (@spikeheap)
- [x] Book The Story Museum  (@spikeheap)
- [x] Find speakers

#### PHPOxford ❤️ 
- [x] decide a start time (phpox is 7.30, we're 7)
- [x] share show and tell form
- [x] write speaker organisation email
- [ ] Oxford geeks?

**Comment by spikeheap** [comment]
This has been moved to September, because summer.

**Comment by rjmunro** [comment]
When in September?

**Comment by benfoxall** [comment]
ha!

**Comment by AverageMarcus** [comment]
Would be nice to do a Summer of Hacks round up as part of this :)

**Comment by benfoxall** [comment]
@AverageMarcus agreed - we're going to have a show and tell, so could maybe roll it into that.
