### ISSUE TITLE
[cancelled] October Talks 19/10/2016

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#215]
#### Theme

TBA, and cake
#### Date

Wednesday 19th October 2016, doors open 7:00pm, talks start at 7:15pm
#### Speakers
- **TBA** - TBA
- **TBB** - TBB
- **TBC** - TBC
#### Core actions
- [ ] Create meetup event & announce
- [ ] Confirm sponsorship for snacks/drinks (@spikeheap)
- [ ] Book The Story Museum  (@spikeheap)
- [ ] Organise speakers

**Comment by benfoxall** [comment]
We're cancelling this event (moving to Feb)
