### ISSUE TITLE
November Talks 23/11/2016

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#216]
#### Theme

Max

#### Date

Wednesday 23rd November 2016, doors open 7:00pm, talks start at 7:15pm

#### Comperes

- @ISNIT0
- Adam Leskis?

#### Speakers

- **Cardboctober** - Max
- **React** - Roger

#### Community Session

…

#### Actions

- [ ] Create meetup event & announce
- [ ] Confirm sponsorship for snacks/drinks (@spikeheap)
- [ ] Book The Story Museum  (@spikeheap)
- [ ] Organise speakers

**Comment by benfoxall** [comment]
Meetup created (not announced) https://www.meetup.com/JSOxford/events/235323309/

Before announcing:
- [ ] intro text (@lpmi-13 - do you want to add some)
- [ ] @omgmog to supply talk description (#232)

**Comment by benfoxall** [comment]
# ❤️
