### ISSUE TITLE
Write speaker details page

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#217]
We usually send this out, though it would be handier to have it in a public place

**Comment by richardwiggins** [comment]
MKGN speaker guide: https://mkgeeknight.co.uk/speakers-guide

/ @benfoxall @spikeheap

**Comment by AverageMarcus** [comment]
The MKGN page is really good! One thing I've noticed it's lacking (if we decide to use it as inspiration and for @richardwiggins benefit) is whether the speaker uses their own laptop or not and if so, what connectors are available.

**Comment by richardwiggins** [comment]
That's a really good shout @AverageMarcus. Maybe we'll add something along those lines on our page.

**Comment by benfoxall** [comment]
I've enabled the wiki and created a page based on the mkgn structure - https://github.com/jsoxford/jsoxford.github.com/wiki/Speaker-Info 

Anyone feel free to add stuff

**Comment by omgmog** [comment]
This is resolved by there being a wiki page now I guess? Cool? Cool. (tidying up issues!)
