### ISSUE TITLE
Pop-up banners

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#219]
In order to let attendees know where the event's happening without needing someone stood on the street, we need to procure 2 pop-up banners with JSOxford logos.

We have ~£50 budget for this, and it looks like [there are options available in that price range](http://www.helloprint.co.uk/rollupbanners-85x205-footbestprice-2-days5#final). 
#### Design

We'll need the banners to have:
- The standard horse, lasery of course.
- The JSOxford logo
- Space for us to stick/tape an arrow pointing in the direction of the event

**Comment by AverageMarcus** [comment]
Those roll up banners... pretty sure theres a good chance they'll blow away.

**Comment by danielthepope** [comment]
Yeah, they're not really for outdoors - you'd want something more like an A-frame sign and a couple of laser horses on pieces of paper.
e.g. https://www.amazon.co.uk/-Board-Pavement-Display-Board-Sign/dp/B003VUY3P4/ref=sr_1_1?ie=UTF8&qid=1463990670&sr=8-1&keywords=a-frame+sign

**Comment by AverageMarcus** [comment]
Anyone good at chalk art? 😉  https://www.amazon.co.uk/dp/B00VKQTLD0?psc=1

**Comment by omgmog** [comment]
We now have a flag, and the JS OxHack popup sign thing from Render 2017.

This is totally sorted, so will close and it can be re-opened if any further work is needed.
