### ISSUE TITLE
SoH stickers

### ISSUE THREAD

**Issue by danielthepope** [jsoxford/jsoxford.github.com#220]
To make this event officially awesome, we need stickers.

To discuss:
- [x] Place to get stickers from at a good price
- [x] Size
- [x] Designs
- [x] How many stickers?

We also need them by the 11th June.

**Comment by danielthepope** [comment]
First site I've seen: https://www.stickythings.co.uk/round-labels-stickers/premium-paper/49mm-diameter-round
Looking at the SoH logo, it looks like a round sticker. 100 49mm diameter stickers for £26.40 (or 250 for £30).
I'm rejiggling the logo a bit to try and fit it on that size.

For size reference, have a look at my laptop (15" screen)

The Codebar and Blubolt round stickers are both 50mm diameter, the laser horse is 70mm square (probably a bit too big), the little hexagons are also 50mm in height, the big hexagons are 75mm and the Bath Hacked one is 100x40mm.

![20160523_163542727_ios](https://cloud.githubusercontent.com/assets/5173183/15477652/abbed34c-210d-11e6-86f3-a1e1d7a00bcb.jpg)

**Comment by omgmog** [comment]
If you want a nice emoji set, the [Twemoji](https://github.com/twitter/twemoji) from Twitter are lovely. Here's a quick sticker I've whipped up using them: 
![soh_sticker1](https://cloud.githubusercontent.com/assets/50949/15477836/db0b7988-210e-11e6-8a55-eebf2f35d471.png)

**Comment by danielthepope** [comment]
:heart: Twemoji - modern, simple, scale well and I already have them all downloaded :wink:
I used them on my trntxt presentation

**Comment by omgmog** [comment]
Here's the SoH logo thrown into a circle.
![soh_sticker2](https://cloud.githubusercontent.com/assets/50949/15477924/4fe3ffd2-210f-11e6-8e67-5d558ac0e51c.png)

**Comment by danielthepope** [comment]
I embiggened the sun
![soh-sticker](https://cloud.githubusercontent.com/assets/5173183/15478053/f3d0fe4c-210f-11e6-8790-7144786fc4a1.png)

**Comment by omgmog** [comment]
Worth noting the yellow is `#fff200`

While I'm churning them out, an abstract one based just around the :sunny: emoji:

![soh_sticker3](https://cloud.githubusercontent.com/assets/50949/15478061/fad51ac0-210f-11e6-86ca-ae103578b169.png)


And that got me thinking, there could be per-event stickers, _Gotta catch 'em all!_:
![soh_sticker4](https://cloud.githubusercontent.com/assets/50949/15478072/0a4479ec-2110-11e6-950a-ade808241171.png)

**Comment by danielthepope** [comment]
Maybe have the individual event ones on smaller squares, with the emoji in the middle? The extra yellow could be a bit unnecessary.
From what I understand of the website, if I order 250 small squares, I can provide lots of images and they'll make an even number of each at the same original price.

Some relevant emoji, all for the yellow background. Perhaps the lightbulb could do with a white border?

![1f916](https://cloud.githubusercontent.com/assets/5173183/15478672/9fbd40aa-2113-11e6-8339-6defc4eb2e22.png) ![1f3ae](https://cloud.githubusercontent.com/assets/5173183/15478706/d4efed40-2113-11e6-97a3-32231b9c7597.png) ![1f4da](https://cloud.githubusercontent.com/assets/5173183/15478740/0048e730-2114-11e6-85ba-2e5e93b7e6d0.png) ![1f393](https://cloud.githubusercontent.com/assets/5173183/15478748/161e3d8a-2114-11e6-8f3c-66ddc9768061.png) ![1f392](https://cloud.githubusercontent.com/assets/5173183/15478784/58a7117c-2114-11e6-93d2-ce225f6337aa.png) ![2699](https://cloud.githubusercontent.com/assets/5173183/15478806/8fce2438-2114-11e6-884b-2704542830a6.png) ![1f680](https://cloud.githubusercontent.com/assets/5173183/15478820/a3461ca0-2114-11e6-8662-404a0e072c25.png) ![1f4a1](https://cloud.githubusercontent.com/assets/5173183/15478879/feed94e8-2114-11e6-94ed-a06e7fe22636.png)

**Comment by omgmog** [comment]
that sounds good. :100: :+1:

**Comment by danielthepope** [comment]
I wonder what would happen if we tried to order a bunch of round SoH ones, loads of little emoji and some bigger square laser horses? Anyway I can't do this today... Back tomorrow!

**Comment by benfoxall** [comment]
**OH MAN**.  This is so *on point*.

Have I got this right? We have some big (ish) stickers for SoH, then some smaller emoji ones that you can only pick up at the relevant event?

![img_20160525_111002](https://cloud.githubusercontent.com/assets/51385/15536668/41a00914-226a-11e6-8bbe-03f1dbd0fba8.jpg)

@omgmog / @danielthepope, even if I've got that wrong - consider it signed off - stickers for the event would be perfect. Let us know exactly what you want bought, and I'll order it - or keep a receipt and we'll get it back to you (would £40 be a good target?)

My one input would be that quality matters - having a sticker that rubs off or fades is worse.  Maybe the bigger SoH ones could be higher print quality and the event-specific ones a bit lighter?

**Comment by peterjwest** [comment]
Yes! What Ben said, this is perfect.

**Comment by omgmog** [comment]
That's exactly what I had in mind, and I'm sure @danielthepope too!

**Comment by peterjwest** [comment]
Can you guys find somewhere to get them, and work out how much they'll cost? Ideally We'd like one for each attendee, so about 100-150. Then as many emoji ones as we can afford.

**Comment by omgmog** [comment]
http://www.discountstickerprinting.co.uk/adhesive-stickers-labels/vinyl-stickers.html

Minimum order of £50, but should be doable if we need 150 of the big one, and then enough of each small one for each event.

**Comment by danielthepope** [comment]
@omgmog That's a good looking site. Using the quote finder I did this
![image](https://cloud.githubusercontent.com/assets/5173183/15549610/56546824-22a5-11e6-8a23-9a6c1435c556.png)
Not sure about what people think about quantities? Also @peterjwest is there a laser horse SVG available?

**Comment by omgmog** [comment]
So long as there's enough for each attendee to get:

- soh circle
- laser horse
- one of each for the event they're attending

Sounds good to me

**Comment by peterjwest** [comment]
I'd say keep it at 2 sticker designs for each event. Also add another 5 for each type, so we have some spares.

Here's the JSOX svg:
https://www.dropbox.com/s/sdgdossrxfbc5e5/logo.svg?dl=0

**Comment by danielthepope** [comment]
@omgmog Just looked at discountstickerprinting again. Looks like that minimum £50 order is actually £50 PER DESIGN. I want 10 different designs, so £500?
NOPE NOPE NOPE NOPE

**Comment by danielthepope** [comment]
In the meantime though, I now have these wonderful assets. I think they're going to look awesome.

![camping sticker preview](https://cloud.githubusercontent.com/assets/5173183/15591927/f45d5f1a-2397-11e6-969d-1fde8c0b2337.png) ![computer sticker preview](https://cloud.githubusercontent.com/assets/5173183/15591928/f464d218-2397-11e6-8b05-53aa6c08879a.png) ![game controller sticker preview](https://cloud.githubusercontent.com/assets/5173183/15591929/f4661150-2397-11e6-8d82-5879f2fbcbeb.png) ![graduation sticker preview](https://cloud.githubusercontent.com/assets/5173183/15591930/f4687ddc-2397-11e6-8d14-31b07e5ee980.png) ![robot sticker preview](https://cloud.githubusercontent.com/assets/5173183/15591931/f46a70e2-2397-11e6-8759-50677d0027a8.png) ![books sticker preview](https://cloud.githubusercontent.com/assets/5173183/15591934/f47cd2dc-2397-11e6-89a4-ed4d78c88dd7.png) ![space invader preview](https://cloud.githubusercontent.com/assets/5173183/15591961/15c5d68c-2398-11e6-868e-bacb38141aa6.png) ![rocket sticker preview](https://cloud.githubusercontent.com/assets/5173183/15591993/45807df0-2398-11e6-9d4e-e04af4173c33.png)

**Comment by danielthepope** [comment]
Asked for a quote from http://www.printpallondon.co.uk/...

**Comment by omgmog** [comment]
That's a shame about the pricing! The designs look great though, hopefully you can find a nice price to get them done!

**Comment by spikeheap** [comment]
This is awesome guys, :+1: to everything, many times.

**Comment by danielthepope** [comment]
In the fairly likely case I need to reduce the number of designs, I personally prefer the rocket (over robot), books (over graduation), game controller (over space invader) and campsite (over computer).
http://www.nuttyprint.co.uk/matt-stickers-round.html will do up to 4 designs for the same price, and they seem very reasonable.
Does anyone have any strong feelings for or against this?

**Comment by danielthepope** [comment]
With Nuttyprint, we have the question of quantities. I can order in batches of 25, 50, 100 or 200.

With the small stickers, the price difference between 100 and 200 stickers (25 or 50 of each design) is negligible (£14.40 vs £15.60), so I'd prefer to get the higher number and have too many stickers than too few.

The larger stickers are different though. We're looking at £14.40 for 100 or £24 for 200, which is annoying because ideally we want 150 of both designs.

I guess it's a matter of how many people will be coming to these events? A lot of people will come to more than one event, a fair few will only attend one, and then there are the people who (God forbid) don't care about stickers.

So the total prices (inc VAT & delivery)
200 emoji + **100** SoH = £35.94
200 emoji + **200** SoH = £45.54
200 emoji + 100 SoH + 100 Laser Horse = £50.34
100 emoji for all the above, take £1.20 off. No point.

What do you think?

**Comment by danielthepope** [comment]
As far as sizing is concerned, this is what they'll look like. Ignore the laser horse, I got that from Redbubble.
![stickers on laptop sm](https://cloud.githubusercontent.com/assets/5173183/15620971/a15ecf56-2455-11e6-9881-1090b0d3cdf9.jpg)

**Comment by spikeheap** [comment]
Hi @danielthepope, good effort on this. I'm pretty excited about stickers right now. That probably says quite a bit about me and how exciting my life is!

Everyone loves a laser horse, so how about:

200 emoji + 200 SoH + 200 Laser Horseys = £60? 

The Laser Horse stickers are a bit off-topic, but it would be great to have a batch to hand out to speakers, etc. (and you guys, of course).

If we have extra SoH stickers they'll either get snaffled at the evening events or we can use them next year.

Thanks again for making this happen!

**Comment by danielthepope** [comment]
@spikeheap The total cost for that would be £63.60. Good idea to stockpile - this might well be enough stickers for next year as well ;)
I'll wait for the go-ahead from @benfoxall and @peterjwest as well, then if someone could Slack me their address I'll get the stickers delivered there. Unfortunately I can't make it to Nodeschool anymore...

**Comment by peterjwest** [comment]
Awesome, yes go ahead with this! Please send to the [WO office](https://www.whiteoctober.co.uk/) addressed to me.

**Comment by danielthepope** [comment]
Stickers ordered :) Apparently they should arrive on Wednesday.

**Comment by omgmog** [comment]
I can't wait! :100:

**Comment by danielthepope** [comment]
Stickers have arrived:
https://twitter.com/JSOxford/status/739736246147284993
Closing the issue 🎉

**Comment by peterjwest** [comment]
Remember to get us an invoice/receipt

**Comment by danielthepope** [comment]
I've sorted that already with @spikeheap :)

**Comment by omgmog** [comment]
Adding this for @ninjanails 
![losergdd](https://cloud.githubusercontent.com/assets/50949/17053354/7406c4c6-4ff9-11e6-97f2-5c66a2f87cb3.png)

As she can't make it tomorrow.
