### ISSUE TITLE
Summer of Hacks 2016 #1: NodeSchool retro

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#222]
Any observations/comments would be appreciated. Especially with some kind of action that we can take forward.
---

Add a comment to this issue, and we'll update the main body to gather everything together

**Comment by AverageMarcus** [comment]
The placement of the tables sucked! May have been better with one long row.

**Comment by richdouglasevans** [comment]
I wanted to come to this but it was oversubscribed so I went exploring Ye Olde English Henges instead. Which was totes cool but it turns out that there were spots available and those standing stones are still gonna be there next weekend.

My takeaway is that if the event is oversubbed, I should just turn up anyway. Is that fair or is that not cricket? The worst that can happen is that I get turned away which is fine. Still, I don't want to put folks in the position of having to turn me away.

Anyways, I trust y'all had fun. Cya at the next one... I am signed up for that one. :smile:

**Comment by spikeheap** [comment]
### What went well

- We had at least 3 beginners, which was awesome.
- A lot of attendees hadn't been to any SoH events and some hadn't been to any JSOxford meetups before. 
- Everyone seemed to have a good time and there was a lot of concentration in the room. 
- Starbucks were great and needed very little notice for refills. Being just round the corner it was really convenient too.
- Burritos went down well, as did the beers.
- The end of day retro was cool. I enjoyed finding out about the side-projects that had been going on.
- The setup. Thanks to Adam and Jonatan who turned up first for helping shift tables. It was easy to get up and running.
- We provided someone with a laptop for the event. Setting up an account on OSX and letting someone loose on it for the day was surprisingly easy and low-risk, and it felt good to help lower the barrier to entry for the day.

### What could we change?

- The layout could be improved to encourage more interaction and feel less clunky. I'm not sure how though.
- We need to bring a projector for the intro (or get the venue to provide one).
- Quiet music might help make the event feel less formal. I'd be interested to get feedback from attendees on whether that would have been nice or just impeded concentration.
- The lack of a kitchen or separate area meant everyone stayed seated most of the day. This was good for concentration, but maybe less good for getting everyone to know each other.
- The venue opens at 9am, so we should advertise it as 9:15 for 9:45 start to give us time to set up.
- We need bowls, plates, and napkins for lunch and snacks. I totally forgot those.
- Parking. There's one parking space at the venue but Sarah wasn't keen on us using it. If we give them advance notice it _should_ be fine though, and it's a pain to bring the snacks and pastries without being able to park. We should coordinate the pickup next time so one of us swings by everywhere (Pete had to drive back to WO and then cycle in after doing a round).
- Turnout. At one point we had 14 people on the waiting list, but we ended up with 11 attendees of the potential 30, which was a little disappointing. Those that did turn up seemed to get a load out of it and enjoyed the day, but as @richdouglasevans mentions, there would have been plenty of people who were on the waitlist and became a 'yes' the day before or on the day, which is way too late and they probably have alternative plans by that point. I'd hate to think people who wanted to go missed out and yet we had a load of empty seats. My vote is to oversubscribe the event slightly (35 for our 30 cap). We've never had more than 90% turnout so we should be fine with that. Another option is to charge a nominal fee, which does increase turnout but feels a little wrong to me. 
- Prepping the team. I sucked at letting @ninjanails know what was going on in the couple of weeks before the event. We should send out an email to the group that's running the event (or do it through Slack) to summarise what's happening and the last minute logistics.

**Comment by AverageMarcus** [comment]
I wasn't involved in any of the prep stuff but from some comments @spikeheap made on the day it might be nice to have a reusable checklist of things that are needed at each events that includes things like bowls/plates/projector etc. 

Maybe a repo of event prep resources that can be used each time? Or a wiki or something.

**Comment by AverageMarcus** [comment]
Oh, also I agree about the comment on music, @spikeheap. There was a couple times when it was uncomfortably quiet.

**Comment by xmakina** [comment]
RE: Turnout - as a halfway house, I've seen free Eventbrite tickets used at other events. Just having the ticket seems to make people far more committed when they say "attending" rather than just clicking a link from an email

**Comment by xmakina** [comment]
Re: Music - I had my headphones, so I was happy. I can see folks who've not done coding before, the target demographic for these events, finding the silence a bit difficult and I'd be happy to have background music on, but I would ask that it is background. Heck, if one of you guys have Music To Code By maybe bring that along?
