### ISSUE TITLE
Summer of Hacks 2016 #2: Game Dev Day retro

### ISSUE THREAD

**Issue by omgmog** [jsoxford/jsoxford.github.com#225]
Any observations/comments would be appreciated. Especially with some kind of action that we can take forward.

---

Add a comment to this issue, and we'll update the main body to gather everything together

**Comment by omgmog** [comment]
## What went well

- Great amount of promotion/hype leading up to the day meant that all of the places were filled
- Chasing/reminding attendees closer to the day to make sure they were still coming helped transition a lot of people from the wait list to the attending list
- We had a projector!
- We had speakers and I provided a cracking couple of playlists
- We had our youngest attendee to date, and he had a great time
- Nearly everyone, regardless of background/skill level jumped in to using the technology that was promoted/suggested -- this was great and meant that at the end of the day there were some really cool games to demo
- We remembered the stickers
- Important info was upfront, so everybody got on the WiFi and got started ahead of schedule.

## What didn't go so well

- Lunch was ordered quite late in the day, which in turn made the afternoon shorter
- One of the burrito orders got lost
- We ran out of time to present demos in the room as we had ran over, so had to kerfuffle demo in the street while dodging cars and pedestrians
- Starbucks in Oxford didn't have any coffee urns available, so Ben (legend) had to go to Summertown Starbucks to collect some, and bring them back to Oxford


(I'll think of more and add to this)

**Comment by gfwilliams** [comment]
It looks like many teams worked great, but maybe a few people (me included) kind of did their own thing, even though it's loads more fun when everyone is working together. It was definitely my fault, but I wonder whether there could be some change of format that made it less easy for people like me to just sit down and start hacking on stuff :)

Maybe just going around and having everyone say what stuff they're interested in doing (graphics, gameplay, art, networking, etc) might make it easier for people who'd come with an idea to find a way to fit that into a bigger project? (I arrived at 9:45, so it's possible I missed this if you did something like it?)

**Comment by AverageMarcus** [comment]
I kinda liked working on my own as I can go at my own place but I made sure to wander about and see what other people were doing.

Burritos - we should save a copy of the list before going and take some better bags to carry them in (ones that won't fall apart if leaks).

Projector - great to have it but in a really awkward place.

Heat - it was hot. Make the weather better next time.

**Comment by peterjwest** [comment]
@gfwilliams this is more what I had originally intended, but ran out of time preparing for it.
