### ISSUE TITLE
Checklist for hosting evening events

### ISSUE THREAD

**Issue by lpmi-13** [jsoxford/jsoxford.github.com#231]
Hi All,

So this is an attempt to get down a centrali(s/z)ed list of things that need to be done prior to each event. The following is a list of questions/ideas, so please feel free to expand on any/all of these.

-Contact speakers
-Book venue
-Confirm with venue (when?)
-Announce event on meetup page
-contacting haybrook(?)
-create invoicing templates

**Comment by lpmi-13** [comment]
we got more hay

-draft checklist of things for hosts to cover/mention during the event (this one might be too fine grained and unnecessary, but putting it on here for reference)
-What is our general process/approach to speaker relations?
-tweeting about event (when? how often?)
-soliciting ideas for future events (how far in advance, which forums/channels?...social media?)

**Comment by benfoxall** [comment]
Okay - I'd started a wiki page on this:

https://github.com/jsoxford/jsoxford.github.com/wiki/Hosting-Info

@spikeheap would you mind adding that stuff to that page? I think it's going to be a better place to collect this kind of stuff.

**Comment by spikeheap** [comment]
Copied in.

**Comment by omgmog** [comment]
This is now a wiki page :100:
