### ISSUE TITLE
Cardboctober: Making VR experiences for Google Cardboard with JavaScript daily in October

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#232]
In October Ben, Pete and Max built something every day for Google Cardboard using Javascript. 

In this talk Max will talk about how he planned and executed a month of hacks, what worked (and what didn't!) and what he got out of the challenge.

---

- [x] @omgmog to provide description

**Comment by AverageMarcus** [comment]
> ~~Doing~~ Unable to do this talk at Marlow[dev] but happy to do it at JS Oxford at some point too!

**Comment by benfoxall** [comment]
nice work, @omgmog 💯
