### ISSUE TITLE
2017 Events

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#233]
# 🎉 2017

This is the central issue for all 2017 events - meetups/hack-days/drinkups. Feel free to suggest any extra events (especially if you feel like running them!)

### Evening Meetups

* 15th February - Mega Super Meetup Meetup - #237
* 12th April – venue confirmed

### Hack days

* June – Language Hack #236
* TBC – Chatbot Workshop #235 
* TBC – VR Hack
* TBC – Hack Cafe

### Social

* 21th January - non-drinkup
* TBC – maybe-drinkup

**Comment by benfoxall** [comment]
Some things I'd love to see:
* a chatbots hack day - @danielthepope @AverageMarcus, you're into that, right?
* being part of a worldwide/remote hack day (like [node knockout](https://www.nodeknockout.com/))
* drinkups - we've done this once, though a regular evening in a bar might be nice

**Comment by AverageMarcus** [comment]
Yeah totally in to that!

With regards to drinkup, I'd quite like to see some sort of lunchtime thing so our young members aren't excluded. (And so we're not just seen encouraging alcoholism ;) )

**Comment by AverageMarcus** [comment]
Oh, you edited, a trip sounds cool. I'd quite like a group trip to a meetup in another part of the country.

**Comment by benfoxall** [comment]
@AverageMarcus Ah, yeah - I'm all about editing stuff.  Good shout about younger members.  A meetup trip sounds awesome.  That's cool you're into a Chat Hack. :+1:

**Comment by omgmog** [comment]
VR hack day some time next year would be awesome, I'd be up for running that again. But maybe let me not think about it until after November 🎉 

![](https://media.giphy.com/media/l41Ys2DpHb1ypplCM/giphy.gif)

**Comment by danielthepope** [comment]
Yes! Bring on the chatbots hack day! I guess I'd need to learn about actual chatbots rather than just Dobot's hear/respond stuff ;)

**Comment by lpmi-13** [comment]
If anyone is interested in particular aspects to address during said "Language Hack", please to be notifying me them (eg, evaluating readability levels of different texts, generating a corpus, general NLP, creating a gigantic game of chatbot telephone slash Chinese Whispers were each chatbot translates to/from a specific language, etc...). I'm planning to have some ideas and super basic starter-activities ready to go for those who don't come with a specific thing they'd like to work on, and actual expressions of interest would be ideal.

PS - Also planning to have a basic API set up by then returning short sentences with particular features, if that sounds like something fun to play with (eg, returning ten sentences with past perfect).

**Comment by samwhitehall** [comment]
A language hack day sounds _super_ fun. 

Regarding the API, I'm not sure about things in the Javascript world but there's a really nice and accurate NLP library in Python called [spaCy](https://spacy.io/) that I've used a few times -- I'd be quite happy to write a thin API around that for basic things like tokenisation and part-of-speech tagging!

**Comment by lpmi-13** [comment]
@samwhitehall Double Edit: Rich Evans and I have been building out said API and have something (almost) working. Please feel free to contribute if you like!

[Repo](https://github.com/lpmi-13/krump)

**Comment by benfoxall** [comment]
@lpmi-13 @samwhitehall I've created #236 for discussion/planning the language hack day (this issue is more for keeping track of all the events for next year.

**Comment by AverageMarcus** [comment]
So just had another idea, JS pub quiz. 🍻 ❓ 🎤

**Comment by ninjanails** [comment]
An idea of having a woman focused even so for example getting all of the speakers to be woman. 

There are more woman in the DO chat and wanting to come to JS Oxford so could be a good change to try and get more woman to come along to JS Oxford but showing them some awesome Woman with awesome talks 😃  

just an idea thought 😃

**Comment by AverageMarcus** [comment]
You offering to talk then? 😀

**Comment by ninjanails** [comment]
@AverageMarcus  Maybe at some point ;P

**Comment by Rumyra** [comment]
HELLO!! So I did a workshop at Decompress part of the Australian set of conferences. It was a bit like a hack day but super way chill, people came by with stuff they were doing and everyone just hung out. There were some short talks about some things, but really everyone just bought what they were working on and shared knowledge. No theme, no agenda (well like nothing to win - no gain), just good chill times.

I don't know how to articulate this but I want to do something like this.

http://2016.decompress.com.au/

**Comment by lpmi-13** [comment]
Language Hack is a go for June, basically...just need to know which date to aim for. Looks like I could do June 10/17/24 or July 1.

Also in talks with some celebrity co-hosts, so hoping to get this sorted and announced by late May?

**Comment by rjmunro** [comment]
@benfoxall Do you mean a trip to something like the National Museum of Computing at Bletchley?

**Comment by omgmog** [comment]
Superseded by #242 now as it's nearly August.
