### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#234]
/cc @jsoxford/jsoxford-next 

This is a first punt at the new website (discussed almost a year ago #197)

![desktop](https://cloud.githubusercontent.com/assets/51385/20040976/c53d59e2-a461-11e6-9421-dc77c598d550.png)

It's a bit of a sketchy/draft to get the ball rolling (I'm not really happy with the style of the main text).

I guess the objectives of this page:

* encourage people to come along to an event
* show that we're an active group

Would appreciate feedback:
* generally
* if there's something this misses (not specific style tweaks, but content I guess)

**Comment by benfoxall** [comment]
Something that is missing:
* photos - show people what to expect (we've got some pretty sweet ones from @henrahmagix)
* sponsor logos (+ how to sponsor)
* come and speak

**Comment by AverageMarcus** [comment]
I feel it's missing yellow.

Twitter link.

There's a lot of empty space...

**Comment by omgmog** [comment]
Like it, but it _is missing something_ -- I might take a punt at a design if I have time this week!

**Comment by AverageMarcus** [comment]
![image](https://cloud.githubusercontent.com/assets/3384072/20052672/ea324008-a4cc-11e6-9b5d-cc557d73a7d6.png)

**Comment by AverageMarcus** [comment]
I keep looking at it and thinking something is _off_. I think it might be the light blue link text. I don't think it has enough contrast (also its a bit jarring that it doesn't span across the rest of the page)

**Comment by peterjwest** [comment]
I like the departure from yellow, but I agree with Marcus, something is off with Ben's design. Too little colour on most of the page vs. extremely colourful header?  Also the JSOX title has very low contrast.

**Comment by rjmunro** [comment]
IMHO, the "JSOXFORD" and "Max's Birthday..." are too light and low contrast compared to their backgrounds.

Why the fixed width font?

I prefer the @AverageMarcus yellow version because it ties into the rest of the JS world better.

**Comment by danielthepope** [comment]
Love the horse and how the background goes down the whole page. Also I prefer the yellow because of @rjmunro's reasons. The font is an interesting(?) choice - readability might be an issue, and to me monospace doesn't reflect 'friendly'. I think the trend these days was to specify system fonts rather than having custom ones?

But anyway, you wanted content feedback instead of styles 😉 

Are we doing away with the blog? I know we haven't written it in over a year but I wouldn't want to see it disappear.

**Comment by spikeheap** [comment]
I'll echo the points already made, ish:

1. I really like the header as a concept, particularly that the rainbow lasers extend into the page. I think it looks more JS-y in yellow.
2. +1 to the need for title and heading contrast improvements.
3. If we're going to have long-form text then monospaced fonts won't be very accessible. If it's just titles and links for things, then it foes feel like it fits with the tech angle.
4. I really like the focus on the sign-up button, and the idea that there's a main call to action on the page (cue Business Cat).
5. The initial design should have more font icons, just to troll @ninjanails :D.

**Comment by benfoxall** [comment]
Okay! Thanks for the input everyone.

So, feedback on the header:

* more yellowy
* better font/contrast

@omgmog has a new version of the header is closer to our current logo style, and addresses both of those issues.  He'll plonk it in here later - and then I think that's us done with the header. (I'm eager to move forward with this and not get lost in discussion/tweaks.) 

So, moving on to the content, comments so far:

* focus on actions to sign up to meetup :+1:
* monospaced :-1:
* there is content we should keep (blog posts)

Also, I'd like to add:

* I think it would be good to move to a list of events rather than blog posts as the homepage.  I think this is better for showing people what kind of things we do and what we chat about.

**Comment by omgmog** [comment]
Current design is as follows, with some tweaks to the sidebar and a design for "listing" type pages (e.g. Blog, and All Events) to come when I have another free moment.

![4](https://cloud.githubusercontent.com/assets/50949/20065946/d76f1bae-a507-11e6-8522-462e79b3cf52.png)

**Comment by ninjanails** [comment]
@spikeheap not funny no icon fonts

The designs look cool and Max's one passes on contract :D

**Comment by AverageMarcus** [comment]
My super crude attempt at mixing things up:
![image](https://cloud.githubusercontent.com/assets/3384072/20075038/915f7f8c-a52a-11e6-8943-c6d7461ae736.png)

Imagine more lasers blending and a lot more icon fonts.

**Comment by danielthepope** [comment]
@omgmog I really like that design.
- I know this was also in @benfoxall's idea as well, but I didn't mention it: I like the focus on the upcoming event. I guess if we have 2 upcoming events we can stick both on there.
- I also like how the 3 previous events are listed as well. We don't need to show _all_ of the previous events, and I wouldn't bother generating pages for all the meetups - we can just point the "all events" link to Meetup.
- Perhaps the upcoming event could do with having the meetup description as well? Might be useful to help the user make their decision on whether they want to press the 'sign up' button. Then again I can see how the description might make the page too cluttered.
- We could do with keeping the social links. I really liked how they are with their icons in the current site.
- Ben's single sentence introduction to JSOxford would be good to have too.
👍 I like where this is going 😄

**Comment by omgmog** [comment]
Feedback taken, I think it's time to get building now. 

With regards to descriptions, I think having a _find out more_ link should be enough, this could either open a modal or just go through to Meetup where we've already got the data. No point recreating all of the functionality on our site.

Cheers guys!
![5](https://cloud.githubusercontent.com/assets/50949/20096656/d2461632-a5a2-11e6-9817-16b0c7dd1db3.png)

**Comment by omgmog** [comment]
This task seems to have stagnated. 

Latest bits are on:
- https://github.com/jsoxford/next-dev
- https://jsoxford-dev.omgmog.net/

So that repo currently contains the basic front-end and some basic Jekyll setup.

Still to do:
- port blog posts over
- some magic to get previous and next events on homepage from Meetup API
