### ISSUE TITLE
JSOxHack @ Render - 30th March (evening)

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#238]
# JSOxHack

This is a hack evening during Render Conf.

We're going to hold it on Thursday night from *6.30pm to 10pm*.

## We're looking for 3 **organisers**:

1. Marcus
2. Someone else
3. Someone else

As an organiser - you'll have a couple of responsibilities:

* to help with the planning of the event, stuff like choosing prizes, making sure our flag is big enough, making sure we're got the wiki/team-list ready
* to run the event on the day - introducing the hack, telling people what they need to do, going round and making sure people aren't stuck, making sure the team list is up to date, running final presentations

## We're looking for _several_ **Hack Leaders**.

As a hack leader, you support a group of up to 5 people - provide them with the bare-bones of a project of your choice.  This might be something like:

* a phaser project template + a gamepad
* a A-Frame project + cardboards
* a multi-user chat room
* a vanilla chatbot
* a web-bluetooth device
* a midi controller & bare-bones js
* an interesting dataset + graph

Before the event - you'll need a brief description of what your hack is about so that people can choose to hack along with you. You'll also have to provide the starting materials for the hack - which should ultimately be a single html/js file (more details on the format of the hack below).

During the event - you'll need to be around to help people if they have any issues with their hacks (it's going to be pretty chilled, so you can totally have a beer/snack while you're doing this).

## The format of the hack

The primary constraint of this event is time.  So everything should be geared to making the most of that.

Each hack should be accessible by a *single url* - it could be the hack itself, or a image url that describes something you've built.

This url should be submitted before the final presentations, there'll be a way to do this in secret to allow you to do a big reveal.

All presentations will be done from the same computer - which will have a list of all the submitted urls.

You can hack on anything, as long as it adheres to the conference code of conduct.

We'll have a series of prizes for given categories (TBC).

**Comment by Rumyra** [comment]
I can make a flag

Like a real one with a pole and sh*t

**Comment by rjmunro** [comment]
Will this be in the venue, or somewhere else?

How about moving the presentations to lunchtime on day 2, so that people can work on the hacks later than 10pm if they want?

**Comment by Rumyra** [comment]
I agree we should do something official in the way of teams and what hacks - the presentations should stay as smooth and quick as pos as it'll be late in the night and people will be tired and well etc...

I am also thinking as there's such a short time of trying to think of a concept to help them with a small hack - try and make the time limit fun somehow

Could we pub quiz a series of micro hacks

**Comment by benfoxall** [comment]
@rjmunro It'll be just outside where the talks are (in that atrium area) and will be going on alongside the drinks in the main hall.  6.30 should be enough time to grab some food (and maybe a beer) before coming back to the hack.

That's an interesting idea about moving the presentations to day two.  It would give people more time, though I'd worry that it could make people feel like they don't want to stick around the whole evening.  It's certainly an option though.

If there were a couple of winning hacks, we might be able to have a very quick demo session on the main stage before a talk on day 2.

Which also reminds me - hopefully we'll get some sponsorship, so we should have some funds to get some prizes.  We'll need a list of what we want.

@Rumyra maybe a github wiki might work for collecting info/teams. Perhaps we could get people filling it out throughout the day with ideas/teams.

I like the idea of micro-hacks. Maybe "Single Page Hacks"?  (SPHs - pronounce the PH as a F sound)

**Comment by AverageMarcus** [comment]
Not sure about presenting on day 2. I'd be a bit intimidated and it'd make it seem more serious than something that (I think) should be relaxing and fun after a long dat of listening to talks.

Prizes... I'd quite like to win an electric skateboard ;) Could we arrange that?

**Comment by omgmog** [comment]
> I like the idea of micro-hacks. Maybe "Single Page Hacks"? (SPHs - pronounce the PH as a F sound)

_Siffs._

![image](https://cloud.githubusercontent.com/assets/50949/22242855/d43c92f2-e21c-11e6-8c0d-ed471ed3a83d.png)

**Comment by benfoxall** [comment]
(oops)

**Comment by rjmunro** [comment]
For the presentations to work smoothly, you need more than one podium with a separate projector input so you can do fast turnarounds. On the cheap you can use two projectors & screens, so you rely on people looking the other way while people get their laptop connected. Ideally you have 2 inputs to a video mixer, each with their own preview monitor, then the user can see that they are working on the preview monitor and know that when the video mixer switches over, their laptop will be working.

Over The Air used to have 3 podiums for presenting hacks, so that 2 people could be getting ready / clearing out when a presentation was happening.

**Comment by benfoxall** [comment]
If it was constrained to single page hacks, and we had a directory of each of the urls that that hack was hosted at, it could make it easier for showing each of them from a single machine (the way that we do show and tell at meetup).

Though a two-input mixer might be an option too.  We won't have the AV team on hand if stuff goes wrong, but hopefully they'd be able to supply stuff if we need.

The OTA setup was awesome!

**Comment by ISNIT0** [comment]
I can provide a projector, if that's of any use

**Comment by AverageMarcus** [comment]
So is the plan to have set challenges from hack leaders for people to attempt? What if someone wants to do something completely different?

**Comment by benfoxall** [comment]
@AverageMarcus I was thinking that the hack leaders are a kind of separate thing. You should just work on your own project, but as a bonus you can also team up with a hack leader to help you out.

**Comment by AverageMarcus** [comment]
Ah ok. So we're not coming up with any ideas? What sort of bare-bones things are you thinking then?

**Comment by benfoxall** [comment]
I've listed a few examples above. It would be up to the hack leader to propose something - so for example I might say:

> **Connected Fairy Lights**
> In this hack - we'll use MQTT to turn fairy lights different colours. You could use it as a way of sending messages to each other (like in Stranger Things), or just make some pretty patterns

What I'd provide is an index.html which has all the boiler plate code for changing the colours of particular lights.

**Comment by AverageMarcus** [comment]
Ooohhhh totally with you now.

**Comment by AverageMarcus** [comment]
Totally awesome fun was had!
