### ISSUE TITLE
The Oxford Mega Super Meetup Meetup Retro

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#239]
It would be really lovely/useful/great to get feedback on the first ever Oxford Mega Super Meetup Meetup.

Feel free to go retro style (stop/start/carry-on/etc), or, whatever you want really. Constructive things would be … constructive.

I guess the big question is: **we should do this again, right?**

(if you have stuff that doesn't belong on this thread - please drop me a DM/email)

**Comment by spikeheap** [comment]
I really want the first comment to be about Ben breaking the projector, so here you go.

**Comment by benfoxall** [comment]
@spikeheap thanks for pointing that out!  I'd like to point out a message that I put in the organisational slack channel:
 
<img width="353" alt="screen shot 2017-02-16 at 09 15 50" src="https://cloud.githubusercontent.com/assets/51385/23032052/1b2322f2-f46b-11e6-8e6d-f01fb1e2aea2.png">

…I guess I can nominate anyone in that channel for not helping out? I choose _you_ @spikeheap, thanks for not bothering to help…

Though yeah - projector issues:

* hdmi didn't work for some laptops
* my mini DisplayPort -> vga adaptor kept on falling off
* laptop wasn't at the right resolution

I guess what we could do:

* bring a Mini DisplayPort -> HDMI adaptor instead (saves switching inputs)
* do actual laptop checks beforehand

**Comment by omgmog** [comment]
The good:
- So many people, so many new faces, and IMHO quite a broad/diverse audience
- 8 talks pulled together with a weeks notice? Awesome.
- Another talk about VR: woah man, we should pretty much have a VR talk every time there's an opportunity for a speaker
- Having a mic was great.

The less good:
- The MC (not pointing fingers) kept breaking the projector
- Perhaps should have sent out projector specs (aspect ratio, resolution) to speakers before hand

It would have been nice to record the evening -- even some low-tech GoPro video would have been good I think. A lot of cool moments in the way these short talks are presented is not being captured!

**Comment by AverageMarcus** [comment]
Yes, we should do it again, it was awesome! 

* Projector - If possible, use a single laptop thats fully charged and set up before people arrive and make sure the speakers understand the mouse setup. 
* Mic was good but better positioning needed
* Drinks / snacks were a bit random / sparse
* More seats if possible

**Comment by danielthepope** [comment]
🍺 One of the guys I was talking to pointed out that this event was very much like the Oxford Geek Nights of old, and that made me think perhaps the next Oxford Mega Super Meetup Meetup should take place in the Jericho Tavern? Then that would solve the problem of finding a pub to go to afterwards, because you'd already be there.
😺 The talks had a good mix of funny, techy and non-techy, and I think that will keep a good range of people coming.
📹 I miss having the talks recorded. I can try and find out if it's possible to borrow a camera/mic from work. Unfortunately I haven't met any camera people - they tend to be in the other building - so that might be a bit difficult.
💻 Windows laptops work really well with projectors :trollface:

**Comment by rjmunro** [comment]
We should go to a quieter pub, or can we just stay at the venue for drinks for a bit longer?

**Comment by Zeus-Moose** [comment]
Projector - Ubuntu worked fine with the HDMI! Having one main presentation laptop is fine if people are doing slides, but if you have live code and similar things it can be much trickier. I though Ben held it together really well despite the minor issues.
Pub - Great fun, as always, but agree finding somewhere where there isn't a quiz on at the same time might be good. Did anyone win the cheese raffle?
Overall, great evening!

**Comment by benfoxall** [comment]
It's been kind of hard to gather together all tweets/messages/photos/etc - this is partly because it happened on separate meetup pages, but also because [#TheOxfordMegaSuperMeetupMeetup](https://twitter.com/hashtag/TheOxfordMegaSuperMeetupMeetup) is a pretty awkward hashtag.

Almost all announcements went out through `@JSOxford`, and the JSOxford meetup page seemed like the central source of talks etc.  I guess this is because I was throwing them together at the last moment, so didn't have time to distribute properly.

I really loved the event.  And I also love the principle of a super-meetup - feels like it's got potential to bring together wider/more-diverse groups of people, and by having several tech group organisers involved it means it's always going to be community focussed/based.
