### ISSUE TITLE
In a web far far away - 3rd of May

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#241]
[todo] intro copy

## The Browser Strikes Back!: The Future Of The Web, Episode 2 - [Peter O'Shaughnessy](https://twitter.com/poshaughnessy)

With the rise of progressive web apps and the latest APIs, web browsers are more capable than ever. So much so, that the word “browser” doesn’t really fit anymore. The web is moving beyond tabs and even beyond our screens. It's now capable of connecting us to the real world around us and transforming us into virtual reality creators.

Back in 2015, I gave a talk predicting what web development might be like in 2020. Now we're (roughly) half-way there, it's time to check in and see what I got right so far, and the big things I missed! As Tim Urban (of 'Wait But Why' fame) says, often the best way to wrap your head around something is to zoom right in and zoom right out. This talk will zoom in on the state of the web today in 2017 - including highlighting our common misconceptions about browsers. And zoom out to see where we've come from - and where we're heading...

## The five stages of JavaScript performance grief - [Simon Hearne](https://twitter.com/simonhearne)

We use JavaScript for everything, but how well do we understand how it performs? There are benchmarks out there for different frameworks, JS engines and libraries that give us an idea. But it becomes much harder to measure performance once we start writing our own code, extending libraries and delivering code to real people.

We often forget that real people have to use our apps. It’s also easy to forget that we are not real people, and that performance benchmarks aren’t run by real people and that real people don’t all have £800 smartphones to run our apps on.
Let’s have a look at the effect that JS has on user experiences, why it is such a critical issue, and some quick wins to improve the experience for those weird real people.

## Community session: Show and Tell - Everyone!

Before announcing / putting in diaries:

- [ ] name & intro copy
- [x] confirm story museum booking
- [x] confirm first speaker - Peter
- [x] confirm second speaker - Simon

**Comment by poshaughnessy** [comment]
For mine, how about...

_Title:_

Browser Revolutions: The Past, Present And (Mostly) Future Of The Web

_Description:_

With the rise of progressive web apps and the latest APIs, web browsers are more capable than ever. So much so, that the word “browser” doesn’t really fit anymore. The web is moving beyond tabs and even beyond our screens. It's now capable of connecting us to the real world around us and transforming us into virtual reality creators.

Back in 2015, I gave a talk predicting what web development might be like in 2020. Now we're (roughly) half-way there, it's time to check in and see what I got right so far, and the big things I missed! As Tim Urban (of 'Wait But Why' fame) says, often the best way to wrap your head around something is to zoom  right in *and* zoom right out. This talk will zoom in on the state of the web today in 2017 - including highlighting our common misconceptions about browsers. And zoom out to see where we've come from - and where we're heading...

**Comment by poshaughnessy** [comment]
Hey @benfoxall, given our chat about the loose Star Wars theme, can I rename mine to:

"The Browser Strikes Back!: The Future Of The Web, Episode 2"    ? :D

**Comment by AverageMarcus** [comment]
I've set a reminder to bring my BB8

**Comment by AverageMarcus** [comment]
> It's a time of uncertainty. Unrest grips the community as people struggle to use all the new shiny browser features while improving performance, but a heroic duo has surfaced to help the resistance rise up.
>
> As they struggle against the dark might of old browsers and low end devices, these brave heroes may yet awaken the skill and strength needed to forge a new future...

https://brorlandi.github.io/StarWarsIntroCreator/#!/AKiiN4j7R4p3NzUyD9HJ

**Comment by AverageMarcus** [comment]
This happened. It was awesome! Everyone seemed to have a good time.
