### ISSUE TITLE
Summer of Hacks 2017?

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#242]
@drarok asked if Summer of Hacks is happening this year:

![image](https://cloud.githubusercontent.com/assets/51385/26317795/9ce20ce6-3f10-11e7-9161-e67a17599528.png)

Basically, there's nothing organised as yet.  Though I think it could still go ahead with it if people are up for running particular events.

Let's make this Friday the deadline for deciding.  If you're able to run an event, and up for it being part of Summer of Hacks - then let's do this.  If we have enough events/interest by Friday then we can get all events in meetup over the weekend, and update the site/announce on Monday.

I really really want to run another summer of hacks, but I can't do it on my own.

Add a reply here or DM me if you're up for running/helping an event, or have any questions/comments.

---

- ~~⭐️ 1st July – **Language Hack** – @lpmi-13 @richdouglasevans~~ (Cancelled)
- ~~⭐️ 19th August – VR Hack – @omgmog @peterjwest~~ (Cancelled)
- ⭐️ 30th September – **JSOxHack** - @AverageMarcus, @omgmog & @benfoxall

- Chat Hack – @AverageMarcus @danielthepope ?
- Hardware – @gfwilliams + ?
- Midi Hack – @Rumyra + ?
- Jam Hacktory – ? (still not heard back from venue)

⭐️ = confirmed

---

Helpful people: @Drarok @garrettc

**Comment by Drarok** [comment]
I might be able to help out, but probably couldn't _run_ an event. What sort of helping out would you need?

**Comment by benfoxall** [comment]
@Drarok cool!  I guess help would be any stuff like helping write meetup descriptions, sharing/posting places, answering attendee questions, deciding plans/timings for the day, picking up snacks/drinks/burritos, giving welcome/introduction for attendees, being there to help anyone with issues on the day.

**Comment by richdouglasevans** [comment]
I'm good to work together with @lpmi-13 on Language Hack. I'll chat with Adam tomorrow about it.

**Comment by gfwilliams** [comment]
I could help with some kind of hardware hack?

I guess rather than a random collection of bits it's better to aim for making something in particular. Is there anyone we might be able to get to sponsor it?

I'd quite wanted to make a laser light show out of lots of individually controlled lasers (so lots of individual units of laser + motor + wifi + battery). Some folks could assemble hardware and others could collaborate on the software to control it all.

Should come in at under £10/unit, so not too pricey. Not quite sure who we could convince to pay for it all though :)

**Comment by lpmi-13** [comment]
We'd like to do the Language Hack Day on July 1, so hope that doesn't conflict with anything else.

**Comment by omgmog** [comment]
Planning with @peterjwest before committing to anything :100:

**Comment by omgmog** [comment]
August 19th: VR Hack (gamedevday) @omgmog @peterjwest

**Comment by benfoxall** [comment]
@gfwilliams that sounds so awesome.  Can I help you with it?  If we can work out a date, I'd be happy to sort out venue & sponsorship and help run stuff on the day (found a pretty nice place the other day).

**Comment by garrettc** [comment]
I'm happy to chip in and help where I can.

**Comment by richdouglasevans** [comment]
Liability Insurance. For a one day event do I want it? Do I need it?

I've not been involved in organising an event such as this before so does anyone have any thoughts to share about this?

**Comment by spikeheap** [comment]
Hi @richdouglasevans, 

With the obvious caveat that I'm not a legal professional, so take everything I say with a pinch of salt, I'd say you absolutely want to consider liability, regardless of the event's length. 

Some venues require you to have liability insurance, or at least to indemnify them against any liability (I'm not sure about the Story Museum, but the OCFI require it), so it may be a pre-requisite to rent the space regardless.

Either way, although it's thankfully very rare, you expose yourself to the risk of being sued if anything goes wrong (or if someone _perceives_ that it's gone wrong). It sucks, but c'est la vie. I know people who don't mind the risk, though I (as you can probably tell by the gist of this comment) feel it's necessary. The flip-side is that if something did go wrong (loads of things come to mind, such as a keyboard becomes sentient and taking out half of the group), it might not be that fair to any victims if they're left without the all important compensation <cue flame war about compo culture>.

There is an alternative to public liability insurance which you might be comfortable with: a liability waiver. Meetup.com talks a little about it [here](https://www.meetup.com/help/article/898492/), and organising one is free (assuming you don't get it checked over professionally). The downsides seem to be:

1. It seems you'd need to get attendees to sign it (although signing digitally may well be fine).
2. You still might get sued, which you'd then need to seek counsel to fight.

Another-nother option is to find a company to sponsor the event who has public liability insurance that includes running events, and get them to take responsibility for that aspect.

Previously we've been covered by my company's liability insurance, but I think we'd be on shaky ground if I'm not involved in the event. PLI is a couple of hundred quid, so whilst it may be worth it as a group, it's probably a bit hefty to take on for a one day event. I have no idea if you can get short-term insurance, but for mine at least the insurance needs to be active both at the time of the event _and_ at the time of the claim. Fun times!

**Comment by lpmi-13** [comment]
Both Story Museum and the Pod already booked for July 1st. Currently soliciting any/all suggestions re: venue

**Comment by richdouglasevans** [comment]
Try the [e-research Centre](https://www.oerc.ox.ac.uk/)?

> Never been there but they do offer courses in their conference room; there's also nothing advertised in their events section for July 1.

> With the obvious caveat that I'm not a legal professional, so take everything I say with a pinch of salt, I'd say you absolutely want to consider liability, regardless of the event's length.

Cheers Ryan for your thoughtful post. I'll crack on with getting insurance sorted then.

**Comment by gfwilliams** [comment]
@benfoxall yeah, that'd be great! I could sort out the hardware and docs for what happens on the day if you could sort out all the actual important bits like venue, sponsor, food, etc?

I think it's something @Rumyra might be vaguely interested in as well? We'd talked about something similar for an event in Bristol but I think it might be a bit late for that now.

**Comment by lpmi-13** [comment]
The language hackday should be unconfirmed. It has been officially cancelled due to lack of venue slash me not getting organised in time.

**Comment by richdouglasevans** [comment]
Disappointing... but this gives us lashings of time to prepare for next year. I'm still 100% behind the thrust of Language Hack Day so let's see this not as a bad thing but as a good thing. ⛅️ 

So, the time to start planning and doing for LHD 2018 is now... @lpmi-13 let's take this over to Slack ⛱ 

@everyon_else are the other hack days confirmed?

**Comment by omgmog** [comment]
VRHack is confirmed, as is JSOxHack.

They'll be officially announced in the coming weeks.

**Comment by kynan** [comment]
Is the language hack day going to be run at a different date or is it officially dead?

**Comment by peterjwest** [comment]
The language hack day had to be cancelled, hopefully it will happen later in the year!

**Comment by omgmog** [comment]
Hack VR is cancelled now because we couldn't find a venue and ran out of time to organise + announce. It'll probably happen later in the year :100:
