### ISSUE TITLE
An Afternoon of JavaScript Oxford

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#243]
Because we've not had a meetup in a while, I was thinking that we could have a full afternoon event so we can fit in more talks/fun.  I've not approached anyone about speaking yet, though I think we've got time for 4 talks; if there's any topics/speakers you'd particularly like to hear, then give me a shout or leave a comment.

As well as publishing this on meetup, I'd like to make a small site with the main info and also lists all speakers and attendees (along the lines of [render hack](http://jsoxford.com/hack/)) - I'm hoping this helps everyone feel more involved with the event, and possibly help session/questions to be more inclusive.

### Dates

* 11th Nov (day after ffconf, not sure if this will impact)
* ~18th Nov~ 
* 25th Nov

### Afternoon plan

1pm -> 5.30pm

* first talk
* show & ask
* second talk
* [break]
* show & tell
* third talk
* some kind of game ??
* fourth talk

---

- [x] set up event page
- [ ] confirm date
- [ ] confirm venue
- [ ] confirm talks
- [ ] confirm post-event meal/drinks
- [ ] publish on meetup

**Comment by benfoxall** [comment]
Microsite - https://github.com/jsoxford/afternoon http://jsoxford.com/afternoon/

**Comment by AverageMarcus** [comment]
I vote for the 11th. Can't make the 25th.

**Comment by danielthepope** [comment]
*digs out the notes he made for a possible longer talk about trntxt and PWAs in general*
This isn't me committing to talk just yet, but this is a topic I'd like to talk about at some point

**Comment by AverageMarcus** [comment]
Great! @danielthepope confirmed for at least one talk! ✅

**Comment by rjmunro** [comment]
I'd love a talk about Cloudflare's new service worker at the edge stuff (https://blog.cloudflare.com/introducing-cloudflare-workers/). Could we invite someone from there to come along? @jgrahamc has talked at Oxford Geek Night before, maybe he can suggest someone.

**Comment by richdouglasevans** [comment]
Shall I go ahead and book the venue? Story Museum, yeah? I can do that tonight -- or attempt to -- if that's where we're having the event. (Might be booked up already on the 11th.)

**Comment by AverageMarcus** [comment]
@benfoxall Is it safe to say this isn't happening?

**Comment by AverageMarcus** [comment]
Sadly this didn't happen 😞
