### ISSUE TITLE
kramdown markup issues

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#39]
We're having issues with headings now that github pages has [been updated](https://github.com/blog/1867-github-pages-now-runs-jekyll-2-2-0).

![image](https://cloud.githubusercontent.com/assets/51385/3869329/4cd53d8c-208b-11e4-9573-d01fb2edbed1.png)

A lot of the posts have been updated on #30 - might be a good time to get that in (ping @carlwood)

**Comment by AverageMarcus** [comment]
I believe this is no longer an issue so closing. @benfoxall please re-open if i'm mistaken.
