### ISSUE TITLE
Untethered NodeBots!

### ISSUE THREAD

**Issue by alanshaw** [jsoxford/jsoxford.github.com#40]
For the last international NodeBots day we created bots that were powered by Node over Bluetooth.

We used this arduino compatible controller (Dagu Arduino Mini Driver Board):
[![mini_driver__79854 1407312618 1280 1280](https://cloud.githubusercontent.com/assets/152863/4020797/7a1d3402-2ad1-11e4-9abe-cea254d98e16.jpg)](http://www.dawnrobotics.co.uk/dagu-arduino-mini-driver-board/)

...and this bluetooth module:
[![screen shot 2014-08-23 at 15 28 19](https://cloud.githubusercontent.com/assets/152863/4020805/c98f3fbc-2ad1-11e4-99a7-885e3c053f05.png)](http://www.dagurobot.com/goods.php?id=128)

You can pair with the bluetooth module and then use node to control it. @achingbrain created this [specialised firmata sketch](https://github.com/achingbrain/footballbot/blob/master/assets/footballbot.ino) to expose just the motors on the board and a [node module](https://www.npmjs.org/package/footballbot) you can use to communicate with it.

**Comment by spikeheap** [comment]
Cheers for the suggestions here, this issue is linked in the NodeBots day issues, so we can close this to keep things clean :).
