### ISSUE TITLE
Arrow-ized FRP

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#43]
> I'd like to order a JSOxford talk for the autumn on Arrow-ized FRP please

https://twitter.com/richdevans/status/516497513285947392

**Comment by richdouglasevans** [comment]
I'm still keen on this topic and I'm good to talk about it myself. But, I'd like to lead into it with a talk about functional programming in JavaScript first using the [Ramda.js](http://ramdajs.com/#) library.

If these topics have traction then I'll run with them for the June meetup? :golf:

Conversely, if they don't have any traction -- the group might prefer to focus on other themes, and that's fine -- then let's bin this old issue. :smile:

**Comment by AverageMarcus** [comment]
I'm interested in this and functional JavaScript. I think having a talk about functional followed by this would be a pretty good set up.

**Comment by benfoxall** [comment]
I've logged this in the talks project - https://github.com/jsoxford/jsoxford.github.com/projects/1 

@richdouglasevans are you still interested in doing this at some point?

**Comment by benfoxall** [comment]
(I've closed this issue for now to try and keep everything together in the github project)
