### ISSUE TITLE
JamHacktory / Hack Factory

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#47]
A day of hacking the [Jam Factory](http://www.thejamfactoryoxford.com/).

The Jam factory has tonnes of interesting connected kit, that we could have access to

* till api
* online reservations / pre-ordering data
* access to till printers
* ethernet connected beer flow api
* cctv
* access to music system
* old hardware - tills, biometric sign in, iphones

Andrew Norton is totally down with this idea, and said they could provide the space, coffee, and access to data from the venue (we should have some kind of agreement - there is potentially sensitive/awesome data available).

**Comment by AverageMarcus** [comment]
Is this definitely going ahead? If so kinda missed the chance to mention it at the last meetup, no?
