### ISSUE TITLE
JSOxford Code of Conduct

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#50]
We don't have an official code of conduct for JSOxford.  Having one will make sure attendees know what is expected of them, and also for potential attendees to know that they are coming to a safe harassment-free environment.

Perhaps we could base it on the [LNUG one](http://lnug.org/code-of-conduct)?  (@andrew / @iancrowther - would this be ok?)

Can anyone else think of anything that we'd want to include?

(thanks @quovixi raising this)

---
- [ ] clearly visible on jsoxford.com
- [ ] linked on meetup.com
- [ ] tweeted

**Comment by omgmog** [comment]
This looks like it has been done.

Code of Conduct is live on http://jsoxford.com/coc/ and linked to prominently
