### ISSUE TITLE
@AverageMarcus - Improving Web performance Using Grunt

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#55]
> In response to a previous talk by Andy Davies on performance I will walk through using [Grunt](http://gruntjs.com/) to improve the performance of the JS Oxford website to achieve below the target 1000 PageSpeed index. This talk will look at configuration-only approaches that can be applied without the need to change any markup.

**Comment by MarcusNoble** [comment]
Could you change it to use @AverageMarcus as this (@MarcusNoble) is my work one

**Comment by AverageMarcus** [comment]
One option is doing a sort of follow up talk to Andy's on using some gunt tasks to improve performance.

I currently use grunt to get 100/100 on Google PageSpeed Insights. Could possibly stretch it to hitting the target 1000 Speed Index.

Could also throw in a little nginx stuff to do with caching etc.

Thoughts?

**Comment by richdouglasevans** [comment]
:thumbsup:

I've never targeted Google PageSpeed before, so I'd like to hear a talk on that topic, sure thing Marcus.

**Comment by benfoxall** [comment]
@AverageMarcus - we're going to put talk titles/descriptions up on meetup this week.  Would you be able to edit the title and issue text for your talk?

Really looking forward to it!

**Comment by AverageMarcus** [comment]
Done! :)

**Comment by AverageMarcus** [comment]
Slides: http://averagemarcus.github.io/grunt-performance-talk
