### ISSUE TITLE
July 25th - NodeBots

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#56]
NodeBots last year was pretty awesome; might be a good time to start organising another one?

https://twitter.com/omgmog/status/571313294910345216
https://twitter.com/Marcus_Noble_/status/571316556023648256

@olizilla / @alanshaw - are there any events happening in London-town that we could link up with around that time?  Or would you be up for another trip up here?

@peterjwest - are you still interested in organising a hack day?  Would you want to run this one?

**Comment by AverageMarcus** [comment]
:+1: 

If anyone is interested in last years NodeBots: https://blog.marcusnoble.co.uk/2014-08-24-nodebots/

**Comment by olizilla** [comment]
We just pencilled in April 11th for the next one. Let's team up!

**Comment by benfoxall** [comment]
@olizilla great stuff; it's a date. Hope tomorrow goes well.

**Comment by AverageMarcus** [comment]
Can we have more structure for this one? E.g. SumoBots (you need to make some kind of bot to push another out of a ring)

**Comment by AverageMarcus** [comment]
Related: #40

**Comment by LuRsT** [comment]
:+1:

**Comment by spikeheap** [comment]
I'm :+1: for structure, but we might want to give ourselves a bit more time than the 11th of April if we're aiming for that. What does everyone think to a sumobots (or similar organised bash) over summer and have a less formal hack in a month?

**Comment by AverageMarcus** [comment]
Summer event? https://github.com/nodebots/nodebotsday

**Comment by benfoxall** [comment]
Having talked about this on gitter - more time to prepare would be good.  Let's do July more awesomely.

**Comment by olizilla** [comment]
We're pushing the London one back too! And as the 25th is **international nodebots day** we should team up on that one for sure. cc: @gorhgorh

**Comment by spikeheap** [comment]
:+1: :+1: :+1: :+1: :+1:

**Comment by AverageMarcus** [comment]
:+1:

**Comment by spikeheap** [comment]
This is covered in #103 now.
