### ISSUE TITLE
April 11th - RTHack

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#57]
We're going to have a hack day using realtime web technologies.

More structure to come, but tech wise we can use stuff like

* websockets
* webrtc
* mesh networks (we've still got some pretty cool hardware for emerging tech weekender)
* chromecast (I'm working on something with this - think we could do some really interesting things here)

---

### LIST OF THINGS
- [x] set up meetup/eventbrite
- [ ] any extra equipment?
- [ ] choose food/refreshments
- [ ] party plans?
- [ ] sponsorship (#74)

**Comment by spikeheap** [comment]
Eventbrite?

**Comment by benfoxall** [comment]
Thought it would be good to charge £5-10 to make sure people turn up, and give us options for food/party funds.  Don't know if you can collect payment on meetup - but eventbrite is all setup at WO

**Comment by matthewhh** [comment]
![jsox-realhack-01](https://cloud.githubusercontent.com/assets/10206482/6616198/6ef5b6ec-c8a3-11e4-856a-8f8e88f03ea0.png)
![jsox-realhack-02](https://cloud.githubusercontent.com/assets/10206482/6616195/6ef53cbc-c8a3-11e4-801c-f3b4d2bac939.png)
![jsox-realhack-03](https://cloud.githubusercontent.com/assets/10206482/6616196/6ef58e06-c8a3-11e4-89e9-05206f19cc13.png)
![jsox-realhack-04](https://cloud.githubusercontent.com/assets/10206482/6616199/6ef5dc76-c8a3-11e4-8251-785bd1dc26c7.png)
![jsox-realhack-05](https://cloud.githubusercontent.com/assets/10206482/6616197/6ef591da-c8a3-11e4-8f26-a819e2182cbb.png)
![jsox-realhack-06](https://cloud.githubusercontent.com/assets/10206482/6616194/6ef53816-c8a3-11e4-9354-5b1acd36e6ff.png)
![jsox-realhack-07](https://cloud.githubusercontent.com/assets/10206482/6616201/6f0aa980-c8a3-11e4-828e-643ec3b0fa6c.png)
![jsox-realhack-08](https://cloud.githubusercontent.com/assets/10206482/6616200/6f08ea82-c8a3-11e4-9774-9fcba0fded19.png)
![jsox-realhack-09](https://cloud.githubusercontent.com/assets/10206482/6616202/6f0b9854-c8a3-11e4-92b6-aa91b168fee0.png)
![jsox-realhack-10](https://cloud.githubusercontent.com/assets/10206482/6616203/6f0b9bba-c8a3-11e4-88e8-95bfbdeecff6.png)

**Comment by benfoxall** [comment]
\o/

**Comment by matthewhh** [comment]
Hello all, take a look a these logos. An idea we had was to make the clock show the actual time on the website. fun!

**Comment by benfoxall** [comment]
@matthewhh these are **so SO AWESOME**! Thanks so much.  I've added numbers if people want to vote for a particular one

**Comment by omgmog** [comment]
7 or 8 look great, and both have the option of being used as a real clock using some css/js magic, perhaps as a count-down to the date, or counting down from the start until the end of the actual day

**Comment by richdouglasevans** [comment]
I like #8 the best. (Though they're all cool!)

**Comment by AverageMarcus** [comment]
I like 8 best :)

**Comment by iiSeymour** [comment]
Also :8:

**Comment by matthewhh** [comment]
Could we use 10 to show the real time and also on the day the strength of the wifi signal? jk

**Comment by omgmog** [comment]
Or something like, number of people that said they would attend vs number of people that have actually attended -- hopefully the "signal" would be full!

**Comment by tomlane** [comment]
:8ball:  :smile:

**Comment by matthewhh** [comment]
How about this, we could add a clock in somewhere, or maybe just flash the time every minute for a 4-5 seconds. 
![jsox-realhack 2-01](https://cloud.githubusercontent.com/assets/10206482/6617776/18c28032-c8b4-11e4-909a-dffac55e2f9d.png)
![jsox-realhack 2-02](https://cloud.githubusercontent.com/assets/10206482/6617777/18ca3e12-c8b4-11e4-83f1-1c25890b12e5.png)

**Comment by omgmog** [comment]
:+1:  :shipit:

**Comment by AverageMarcus** [comment]
So who's the residential CSS master that can throw this together?

**Comment by benfoxall** [comment]
I love this,  though the current time might be a bit confusing - the clock face was a bit more subtle.

**Comment by AverageMarcus** [comment]
I quite like the current time idea. And say every 10 seconds or so have it do the "airport board" spinning thing to show JS RT
e.g. http://www.shutterstock.com/video/clip-716875-stock-footage--d-animation-from-a-airport-billboard-with-the-word-boarding.html

**Comment by benfoxall** [comment]
Perhaps we could have a few things and cycle between them?

```
JS   - 
-    RT

J  S
R  T

RE AL
TI ME

11 04
20 15
```

**Comment by benfoxall** [comment]
Rather than the current time - I'd expect this to be a countdown

```
DA YS
   10

HO UR
S  05

MI NS
   15

SE CS
 2 24
```

**Comment by omgmog** [comment]
I made this, it's bonkers (the pseudo element use) and could do with being made over. http://codepen.io/omgmog/pen/KwGQMP

**Comment by benfoxall** [comment]
OMG @OMGOMG!

**Comment by omgmog** [comment]
@OMGOMG is an imposter, but yes indeed :smile:

**Comment by AverageMarcus** [comment]
Someone has too much time on their hands and not enough work to do ;)

**Comment by benfoxall** [comment]
Ah - I'd totally misunderstood this; thought it was 2x2 rather than 2x1.  Flashing between stuff makes sense.

You're no imposter @omgmog! you **are** jsoxford

**Comment by omgmog** [comment]
![](https://38.media.tumblr.com/96304ccd2c3b8bb9d22d55f650499f5f/tumblr_msp1fjIFNp1sbavuuo1_500.gif)

I was having a productive lunch playing Project Zomboid, but I died, so whipped that up -- plenty busy otherwise!

**Comment by matthewhh** [comment]
You guys are wizards. This is a potential real time clock and new design mash up. 
![screen shot 2015-03-12 at 2 43 34 pm](https://cloud.githubusercontent.com/assets/10206482/6620093/a58f5424-c8c6-11e4-954a-64de06a1abd9.png)

**Comment by matthewhh** [comment]
But I love the airport board idea. There's a lot of potential there and I think once people see that it updates it could be pretty fun. Also, you could add a one or two word heading built in. Date / days until / time / hack day / etc.

**Comment by matthewhh** [comment]
![screen shot 2015-03-12 at 2 55 34 pm](https://cloud.githubusercontent.com/assets/10206482/6620299/e29f0b2e-c8c7-11e4-990a-eb047b8af4d8.png)

**Comment by AverageMarcus** [comment]
http://codepen.io/anon/pen/azRYbY?editors=110

**Comment by matthewhh** [comment]
The font is   font-family: Source Sans Pro;

**Comment by benfoxall** [comment]
Meetup has been updated - http://www.meetup.com/JSOxford/events/221085527/

If anyone sees any issues, could you plonk it in here?

**Comment by benfoxall** [comment]
### schedule
_(comments welcome)_

**9.30** - start (pastries & coffee)
**9.40** - hello, overview of data / tools
**10.00** - project pitching / choosing
**10.30** - kick off
**12.45** - retrospectives
**1.00** - lunch
**5.30** - show & tell
**6.30** - drinks at Joe Perks

**Comment by benfoxall** [comment]
updated [meetup](http://www.meetup.com/JSOxford/events/221085527/)

**Comment by AverageMarcus** [comment]
Looks good. Might be worth having meetup email out the update (if possible?) so people see it.

**Comment by benfoxall** [comment]
Jo perks is booked - and they're going to have a special realtime based cocktail for us

**Comment by AverageMarcus** [comment]
Realtime cocktail? "Lean your head back and i'll just keep pouring"
