### ISSUE TITLE
New Website with Meetup Integration

### ISSUE THREAD

**Issue by AverageMarcus** [jsoxford/jsoxford.github.com#59]
Me and @benfoxall spoke a little last night about revamping the JS Oxford website but making use of the [Meetup API](http://www.meetup.com/meetup_api/) to prevent duplication etc.

Thoughts?

Related: #28, #27

**Comment by spikeheap** [comment]
:+1:

**Comment by peterjwest** [comment]
That would be great

**Comment by AverageMarcus** [comment]
A quick test this morning (https://github.com/AverageMarcus/MeetupIntegrationTest) shows it should be pretty easy.

**Comment by benfoxall** [comment]
This is awesome - really interested in getting this live (as I said in gittter - I think we should be planning for a big over-haul, and we should chat about it at some point)

**Comment by AverageMarcus** [comment]
Yeah I'm all up for meeting up to chat about it!
