### ISSUE TITLE
@peterjwest talks about testing javascript.

### ISSUE THREAD

**Issue by AverageMarcus** [jsoxford/jsoxford.github.com#61]
> I'd be happy to do a talk on clojurescript or testing javascript.
 - @peterjwest [Source](https://github.com/jsoxford/jsoxford.github.com/issues/54#issuecomment-82253643)

May meetup?

**Comment by richdouglasevans** [comment]
:+1:

Of the two suggestions, I favour the ClosureScript one. I just stumbled across [the Jest tool](https://facebook.github.io/jest/) though, so clearly I have much to learn with regard to testing in JavaScript: I have been using raw Jasmine like some kind of peasant.

**Comment by AverageMarcus** [comment]
I'm quite keen on either (both?). :smile:

**Comment by benfoxall** [comment]
We did have a talk about closurescipt last year.  Perhaps we could go for a testing theme - that way @spikeheap could get #44 off his chest too

**Comment by spikeheap** [comment]
:+1:

**Comment by peterjwest** [comment]
Testing one suits me better, I'd have to relearn clojure to do the other.

I can cover: mocha (better than jasmine), sinon, chai, nock, supertest, istanbul, phantomjs and protractor
Could maybe cover hooking it all together with gulp.

**Comment by richdouglasevans** [comment]
I've never heard of nock, supertest, or istanbul so this sounds le+cool!

As for the "gulp hookup," sure thing, your talk your call; but I'd not want to see a bunch of slides that dump snippets of Gulp at me 'cos I can get that on t'web. (Although if you can make the Gulp stuff as exciting as macramé I'm all in!) I'd rather have deeper than broader, so just test tools as opposed to test tools + build tools.

**Comment by AverageMarcus** [comment]
:+1:

**Comment by tomlane** [comment]
:+1:

**Comment by AverageMarcus** [comment]
@peterjwest would this be for the May meetup? If so shall we check that @spikeheap can do his talk then also and set up a new ticket for that meetup?

( :open_mouth: meetup planned 2 months in advance?)

**Comment by spikeheap** [comment]
Sounds good. What dates are we thinking?

**Comment by richdouglasevans** [comment]
May 21st!!!1! That would be a super awesome date because of birthdays and all.

**Comment by AverageMarcus** [comment]
Would that mean :cake:  ?

**Comment by richdouglasevans** [comment]
:cake: _and_ :beers: :laughing:

**Comment by peterjwest** [comment]
Yeah for may is fine.

**Comment by richdouglasevans** [comment]
Here's [Wallaby.js](http://wallabyjs.com/), the test runner that I mentioned as we scarfed burritos in the carpark yesterday. It's only for (JetBrains IDEs) such as [WebStorm](https://www.jetbrains.com/webstorm/) at the moment, but integration with Visual Studio and Sublime is in the works. I don't know that you'd talk about it, but it's worth a look at.

**Comment by LuRsT** [comment]
:+1:

**Comment by peterjwest** [comment]
Thanks, I'll have a look.
