### ISSUE TITLE
2015-05-14 - Tests

### ISSUE THREAD

**Issue by AverageMarcus** [jsoxford/jsoxford.github.com#62]
#### Date
May 14th

#### Speakers

@peterjwest #61
> I can cover: mocha (better than jasmine), sinon, chai, nock, supertest, istanbul, phantomjs and protractor
Could maybe cover hooking it all together with gulp.

@spikeheap #44
> Ryan Brooks – The most convoluted JavaScript testing framework?
> Ryan wants to talk about an abomination he built to test JavaScript running on the Rhino JavaScript engine, and how an optimistic "of course you can test that, it's just JavaScript" led to a rabbit hole and lost sleep.

#### Core actions
- [ ] Confirm sponsorship for snacks/drinks (@spikeheap)
- [ ] Confirm availability of White October (@benfoxall)
- [x] Organise speakers

#### Event organisation
- [ ] Ensure someone has carried out the actions above
- [x] Add to MeetUp.com (just prior to preceding event)
- [ ] Announce event

**Comment by benfoxall** [comment]
ace!! @AverageMarcus do you want to lead this one?  Involves introducing talks, and generally being in control of stuff.

**Comment by AverageMarcus** [comment]
Yeah, why not? 

May need a little guidance in what I need to do in the run up.

**Comment by benfoxall** [comment]
\o/  - cool!

**Comment by spikeheap** [comment]
Happy to help @AverageMarcus :+1:

**Comment by AverageMarcus** [comment]
:smiley: 

@spikeheap / @peterjwest - when you have a title and description for your talk can you update this issue with them please?

**Comment by benfoxall** [comment]
I'll probably be a bit delayed (down in London for [TalkWD](http://talkwebdesign.co.uk/)).

@elucas @garrettc @Drarok @olorton @rjmunro - would any of you be able to stick around to help with setup?

**Comment by AverageMarcus** [comment]
I'm happy to show up early to help set up.

**Comment by elucas** [comment]
Yay! Count me in for chair+desk moving etc :)

**Comment by benfoxall** [comment]
Ace! thanks @elucas

**Comment by Drarok** [comment]
Only just seen this, sorry. Is JSOxford moving to Thursdays? Happy to help out if so, can't to the usual(?) Wednesdays.

**Comment by AverageMarcus** [comment]
Guess I should make sure @peterjwest is OK with the new date so we can line up with digital Oxford week.

**Comment by benfoxall** [comment]
## New date - May 14th

Switching to may 14th to align with digital oxford week.  Can everyone make it?

- [ ] @AverageMarcus 
- [ ] @peterjwest  
- [ ] @spikeheap  
- [ ] @elucas 

Once we can, let's create the meetup

**Comment by peterjwest** [comment]
I'm good, sorry been ill for a few days.

**Comment by AverageMarcus** [comment]
@peterjwest Hope you're feeling better. Would you mind putting a summary together before RTHack? Want to get the next meetup event up so we can mention it to people.

**Comment by benfoxall** [comment]
@AverageMarcus you should now have access to the draft meetup:
   http://www.meetup.com/JSOxford/events/221556244/

I guess the things you want to tweak/add are:

- [ ] title
- [ ] intro / description
- [ ] @peterjwest's talk
- [ ] @spikeheap's talk (see #44)

No rush - but would be cool to have it announcable for next RTHack!

**Comment by AverageMarcus** [comment]
Awesome meetup everyone! :+1: 

Thanks @peterjwest  and @spikeheap
