### ISSUE TITLE
JSOxford deployment tidyup

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#64]
Following on from @AverageMarcus's excellent PR #63, I/we need to streamline the deployment and finish up:
- [x] Create Travis job to build and deploy on each change (daily)
- [x] Update the Readme with steps to reproduce, branch meaning, etc.
- [x] Compile single CSS for externals, so we can uncss is and save a few Kb.
- [ ] Set up CloudFlare
- [x] Move Meetup integration into build step. 
  - [x] Sprite all members images.
  - [x] Create Jekyll files for all meetup posts (#109)

**Comment by AverageMarcus** [comment]
Be careful with point 3 as it would mean losing the benefit of people having Bootstrap cached.

**Comment by spikeheap** [comment]
That's true, but for those that it's not cached for anyway we'd save extra network round-trips as well as a bunch of bytes. On my site the Bootstrap CSS, concatenated with my additions and uncss-d went down to 347 bytes (from over 24.4Kb) - small enough to inline in the head and completely remove any CSS network calls...

**Comment by AverageMarcus** [comment]
I guess we are only using a tiny bit of bootstrap anyway.

**Comment by AverageMarcus** [comment]
Only thing left is to set up cloudflare.

**Comment by omgmog** [comment]
Cloudflare should be simple enough:

- For a free account you'll need an email address that hasn't been used before, so for this I'd recommend setting a mail forwarder somewhere for *@jsoxford.com -- I could sort that out on my atmail account if you'd like
- Create Cloudflare account
- Change DNS for domain over to Cloudflare
- Set rules for the domain to enable Flexible HTTPS, enable js/css/html caching and compression
- Remove all of the optimisation tasks from the gruntfile

Should take about 20 minutes of somebodies time

**Comment by AverageMarcus** [comment]
> Remove all of the optimisation tasks from the gruntfile

What do you mean exactly by this?

**Comment by omgmog** [comment]
the `cssmin` and `htmlmin` tasks won't be necessary because the pagespeed stuff provided by Cloudflare

**Comment by AverageMarcus** [comment]
But does it negatively effect? There's still the first hit to take into account.

**Comment by omgmog** [comment]
Handing off the optimisation to Cloudflare, and removing an upfront processing task is a good move. The average end user will get the optimised version from Cloudflare, and never the unminified versions from Github.

My thinking is that it would be better to reduce dependencies and premature optimisation in the codebase, and if we're going with Cloudflare to fully utilise it.

Uglifying CSS/HTML/JS just really moves the burden from bandwidth to processing, which is good/bad for mobile users (bandwidth good, battery bad).

**Comment by AverageMarcus** [comment]
Oooohhhhhh! Does CloudFire minimize?

**Comment by omgmog** [comment]
Yep, as well as caching on their CDN

![](https://i.imgur.com/CxQsJLc.png)

**Comment by AverageMarcus** [comment]
Totally didn't know that. Yeah makes sense as long as the `uncss` task remains.

**Comment by spikeheap** [comment]
@omgmog I agree with most of the points here, but I think I'm a little confused where you say CSS/HTML/JS shifts the burden from bandwidth to processing – the processing burden for minified/unminified assets will be broadly the same as the symbol size and whitespace don't affect the lexing/parsing phase. 

gzipping the content would increase the processing overhead, so I'd be interested to see how that's offset by the decreased network overhead (which is also expensive for battery). My thought (citation required) is that the network saving from compression more than outweighs the decompression CPU cycles.

I'm a fan of leveraging a CDN, and making the most of their optimisations makes sense, especially if it helps simplify the build process.

**Comment by omgmog** [comment]
![](https://media2.giphy.com/media/12Zl61Sx4JoB2w/giphy.gif)
