### ISSUE TITLE
Switch default branch to `develop`

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#71]
The JSOxford master branch is currently `master`. Could we change it to `develop` please.

## Rationale

We're switching to a grunt-powered, Travis-built site which is then pushed to the `master` branch to be hosted by GitHub pages. As a result, `master` will only contain the built site, not the source code, which will be a tad confusing to contributors. Also, all PRs will need to be made against the `develop` branch in future.

Sometime early this week I'll add the Travis build with a watch on `develop`, so any changes merged into the `develop` branch are automatically built and deployed to `master`.

@benfoxall could you do the switch?

**Comment by benfoxall** [comment]
Done.  It's unfortunate that the `gh-pages` branch won't work for org pages, but yeah - this totally make sense.

**Comment by AverageMarcus** [comment]
@benfoxall you can get around it by changing the name of the repo to something like 'site' but then you have to go through the hassle of updating URLs everywhere.
