### ISSUE TITLE
RTHack sponsorship

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#74]
sponsorship for #57

- [x] space (White October)
- [ ] pastries / snacks - £125
- [x] lunch (burritos) - £150 (Haybrook)
- [ ] swag / prizes
- [ ] after drinks ([Joe Perks](http://joeperksandco.co.uk/) are making a "realtime" themed cocktail for us)

**Comment by AverageMarcus** [comment]
- [ ] JS Oxford t-shirts :stuck_out_tongue_winking_eye:

**Comment by benfoxall** [comment]
firebase aren't able to send us any swag (I got in touch too late), though they have given us a promo code of `oxfordhackday` which gives us a month free credit on their candle plan ($49)

**Comment by spikeheap** [comment]
Hey @benfoxall, @peterjwest, have we managed to secure sponsorship for the pastries or any swag from vendors? Sorry I've been a bit out of touch on this one. If we're a little short, I'll happily throw in £35 to cover half the pastries.

**Comment by benfoxall** [comment]
Ricks don't do the mini pastries anymore, so I've ordered:

* 20xPain au chocolat
* 15xPain au raisin

…to be collected at **8.45** tomorrow morning.  The manager wasn't in to talk about discounts, so worst case we'll get the take out rate of £1.20 (**£42** total), but hopefully they can do us a deal.
