### ISSUE TITLE
RTHack attendee pack

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#75]
This should contain all the info that people need to get started with hacking.

## credentials / details
- [ ] pusher credentials *
- [ ] pubnub credentials *
- [ ] peerjs details
- [ ] firebase details
- [ ] ~~google apps / chromecast login (?)~~
- [ ] pusher feed - twitter
- [ ] pusher feed - JSOxford replies
- [ ] pusher feed - train data

* per team/person

## example api apps
- [ ] pusher tweets
- [ ] pusher train data
- [ ] pubnub drawing
- [ ] peerjs video call
- [ ] peerjs datachannel

## example library apps
- [ ] socket.io
- [ ] faye
- [ ] ~~scuttlebutt (?)~~

**Comment by spikeheap** [comment]
We could drop these into a private gist (1 per attendee)? 

Also for the group docs we could add:
- [ ] Getting started (pointers to good walkthroughs, tutorials and docs)
- [ ] Project ideas (people can PR any suggestions prior to the event and it saves getting stuck with the blank page)

**Comment by tomlane** [comment]
How much rail data would you like? I can setup a subscription to the global country wide channel but it depends on pusher/pubnub limits. 

[It can get pretty busy](http://www.openraildata.com/index.php/NROD_Message_Batching)

**Comment by AverageMarcus** [comment]
Would just the Oxfordshire area be enough?

**Comment by AverageMarcus** [comment]
Might be worth mentioning if we use PubNub:

http://www2.pubnub.com/training-webinars 
**How to use the PubNub JavaScript API**
April 14, 2015 / 9:00am - 11:00am PT

**Comment by spikeheap** [comment]
Hey @benfoxall, how's this coming along? Do we have the content and just need to make up the pack? I've got a little time this evening I could help with that.

**Comment by AverageMarcus** [comment]
I could also help if needed too.
