### ISSUE TITLE
2015-06-10 Practical Open Linked Data Mega Meetup

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#94]
Last year there was a [really good talk at UXOxford](https://vimeo.com/112431910) about the importance of linked data. It would be great to follow that up with talks around the practicalities of consuming and presenting open linked data sources.

This theme definitely lends itself to being a __super mega meetup__. OxRug are onboard (whoop), @LuRsT would you guys be keen to get pythonistas involved?

#### Date
Wednesday 10th June 2015, 7:30

#### Speakers
Leigh Dodds from ODI is keen.
We could do with one more local speaker

We could do with another (preferably local) speaker too.

#### Core actions
- [x] Confirm sponsorship for snacks/drinks (@spikeheap)
- [ ] Confirm venue (@benfoxall, as it's super-mega, we might want to consider a bigger venue for this one...)
- [x] Organise speakers

#### Event organisation
- [x] Ensure someone has carried out the actions above
- [x] Add to MeetUp.com (just prior to preceding event)
- [x] Announce event

**Comment by LuRsT** [comment]
We sure are!

**Comment by spikeheap** [comment]
:+1:, with unicorns and rainbows and such.

**Comment by spikeheap** [comment]
I've added the draft Meetup.com event: http://www.meetup.com/JSOxford/events/221686847/

**Comment by tomlane** [comment]
Happy to fill the gap if needed. 

"Tom Talks About Trains Again" - running draft title.

**Comment by spikeheap** [comment]
This happened.
![igetitofcoursethatwouldbebrilliant](https://cloud.githubusercontent.com/assets/464482/8155284/a6540a4e-133a-11e5-8911-7c70dfe497e9.gif)
