### ISSUE TITLE
2015-07-15 July Event

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#95]
I'm pretty excited about the prospect of a set of JS talks that focus on some of the more creative aspects of the web (mostly because I rarely get to do it).

#### Date
Wednesday 15th July 2015, 7:30pm

#### Speakers
TBA, @benfoxall is on it

It would also be great to get at least one more local speaker, perhaps to talk about JavaScript games, web audio, d3, canvas, animation, or something like that.

#### Core actions
- [x] Confirm sponsorship for snacks/drinks (@spikeheap)
- [ ] Confirm availability of White October (@benfoxall)
- [ ] Organise speakers (@benfoxall)

#### Event organisation
- [ ] Ensure someone has carried out the actions above
- [ ] Add to MeetUp.com (just prior to preceding event)
- [ ] Announce event

**Comment by spikeheap** [comment]
Meetup.com draft event: http://www.meetup.com/JSOxford/events/221686899/

**Comment by spikeheap** [comment]
Hey @benfoxall, how's it going with this? Any chance we could announce this event this evening?

**Comment by benfoxall** [comment]
Sure - let's announce.  Coming back to this, I'm even less sure about "media" title part.  Though everything else works

**Comment by spikeheap** [comment]
"Creative JavaScript"?

**Comment by benfoxall** [comment]
Yeah! Something along those lines would be cooler.
