### ISSUE TITLE
2015-08-12 JSOxhog BBQ

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#96]
You know what goes really well with JavaScript? Barbecued stuff. 

Seeing as we have guaranteed (_yeah right!_) good weather and long evenings, we'll trade speakers for some quality barbecue time and a chance to catch up.

The barbecue is open to all, and we'll have a selection of vegetarian-friendly options as well as the usual meat-fest.

#### Date
Wednesday 12th August 2015, __6:30pm__

#### Core actions
- [x] Confirm sponsorship for venue/food/drinks (@spikeheap)
- [ ] Organise venue (@peterjwest)
- [ ] Organise the food (@peterjwest)
 
#### Event organisation
- [ ] Ensure someone has carried out the actions above
- [x] Add to MeetUp.com (just prior to preceding event)
- [x] Announce event
- [ ] There'll be some setup required

**Comment by spikeheap** [comment]
We could consider charging a nominal fee for this event to help contribute to the food costs and generally ensure that people who've signed up do attend. I wouldn't want this to be any more than the price of a beer (and you'll get one back with the food, so it's good value ;)).

**Comment by spikeheap** [comment]
Link to Meetup.com draft: http://www.meetup.com/JSOxford/events/221686941/

**Comment by AverageMarcus** [comment]
I *love* this!

**Comment by peterjwest** [comment]
We're now going to have regular food at St Aldates Tavern, mainly due to budget constraints.
Have phoned them and now waiting for them to reply to an email.
Moved this to 7pm, since we're not BBQing/outside now.
Will update the issue later.

**Comment by spikeheap** [comment]
This happened. It was pretty good. We should do it again sometime

**Comment by richdouglasevans** [comment]
> We should do it again sometime.

Totes. In the autumn please, I was kinda bummed to miss this one. The JSOxford community is a good one.

Any pics to share of a smiling Ryan tucking into roast beef and yorkies with a cheddar mash and a raspberry coulis?  :smile_cat:

I always like a good foodie pic. @iiSeymour -- of [tacocat](https://github.com/iiSeymour/tacocat) fame -- is pretty good about tweeting pics of delicious food from the many conferences he attends and I love him for it.

**Comment by peterjwest** [comment]
In the end it was just a social, we didn't have enough sponsorship to do a hog roast :(
