### ISSUE TITLE
2015-09-16 Summer of Hacks roundup

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#97]
http://www.meetup.com/JSOxford/events/221687013/

## Date
Wednesday 16th September 2015, 7:30pm

## Speakers
**📢  Making the web more better** – Joe Reeve

Joe works at SquaredUp(.com) using Ractive to build dashboards and improve system administrator's workflows, and he's going to be showing us how we can use Ractive to fix the way we web.

**📢  Digital Manuscript Toolkit** – the journey so far – Monica Messaggi Kaya

An introduction to International Image Interoperability Framework (IIIF) and its use on the Digital Manuscript Toolkit (DMT) - where Monica is working specifically on a JavaScript client to edit manuscripts online (via browser).

**📢  TBA** – Ivan Bokii

TBA

## Core actions
- [x] Confirm sponsorship for snacks/drinks (@spikeheap)
- [ ] Confirm availability of White October (@benfoxall)
- [x] Organise speakers

## Event organisation
- [ ] Ensure someone has carried out the actions above
- [ ] Add to MeetUp.com (just prior to preceding event)
- [ ] Announce event

**Comment by spikeheap** [comment]
Meetup link: http://www.meetup.com/JSOxford/events/221687013/

**Comment by benfoxall** [comment]
Speakers we've talked about:

* Monica - Digital Manuscripts Toolkit, using IIIF and JavaScript
* Joe - Ractive

I'd really like to see @omgmog's cardboard demos - could we try again on a different hotspot?

**Comment by peterjwest** [comment]
Ivan (from B2M) wants to do a talk - either React **or** Closurescript, he wasn't sure which would be better received.

**Comment by omgmog** [comment]
I'd like to try the Cardboard stuff again (new stuff, not the same slides) at some point, so yeah you could pencil me in for a "Cardboard/JS take two".

**Comment by ivanbokii** [comment]
Hi guys, if you think it'd be a good fit I can do a talk on React.js basics and comparison to Angular.js (m.b. Backbone.js too) or ClojureScript.
